icl-utk-edu/papi

PAPI_FAQ.html
README.md
src/components/sde/README.md

Removed some remaining links and references to the former Bitbucket repository and replaced them with the GitHub repository.

remove references to Bitbucket

---

src/counter_analysis_toolkit/main.c

Previously, there were no default values given for the PTS_PER_LX and LX_SPLIT parameters in the ".cat_cfg" file. This caused a floating-point exception in the data cache benchmarks.
These parameters now have valid default values, even if they are not specified by the user in the ".cat_cfg" file.
These changes have been tested on the AMD Zen4 architecture.

cat: fix bug in data cache benchmarks

---

src/components/pcp/tests/testPCP.c

Previously, the test would fail if the PCP component was disabled. These changes check to see if it is disabled, and if so, skip the test.
These changes have been tested on the IBM POWER9 architecture.
Addresses issue #22

pcp: skip test if component is disabled

---

src/components/sysdetect/Rules.sysdetect

This PR adds explicit preprocessor flags to the sysdetect makefile in order to allow the component to find the cuda headers in the system.
_Why_ this PR exists. Reference all relevant information including _background_, _issues_, _test failures_, etc
_Commit_ headers have the form: `module: short description`
_Commit_ bodies contain a detailed description of what problem is addressed and how it is addressed

sysdetect: add include path for cuda headers to makefile

---

src/components/sde/tests/Makefile
src/components/sysdetect/tests/Makefile

This PR addresses issue #24. The problem comes from erroneous flags in the test Makefile of the **sysdetect** and **sde** components for fortran compilers that are neither **gfortran** nor **flang**. More specifically, a Cray fortran compiler build error was reported by the spack project in PR https://github.com/spack/spack/pull/38443. This PR fixes the typo in both
components.
_Why_ this PR exists. Reference all relevant information including _background_, _issues_, _test failures_, etc

2023.06.20 fix fortran test flags

---

src/components/sysdetect/x86_cpu_utils.c

There was a typo in the sysdetect code for the x86 CPU architecture that computed a bitwise AND of two variables using the logic AND (&&) instead of the bitwise AND (&). This patch fixes the problem.

sysdetect: replace logic AND with bitwise AND operator

---

.github/workflows/main.yml
.github/workflows/spack.sh
src/smoke_tests/Makefile
src/smoke_tests/simple.c
src/smoke_tests/threads.c

We need to include the required "smoke test" files so that spack can use these to validate the installation of papi.  I put these into `src/smoke_tests`.  Is there a better location?
Once the location and require test environment are set, we can implement the smoke tests within the papi spack package.

Add smoke tests for spack install

---

src/components/perf_event/perf_event.c

With perf_event we can use fast rdpmc reads for low-overhead counter access.  This only works in self-monitoring situations where the thread being measured is in the same process context and same CPU as PAPI.  This means it cannot generally be used in the attach case, or if trying to do system-wide measurements (granularity anything other than PAPI_GRN_THR).
Ideally the Linux kernel would notice the request to use rdpmc in inappropriate circumstances and cause the mmap() read to fail and fallback to using the read() syscall.  However for various reasons the kernel devs did not want to support this, so it's up to PAPI to avoid using rdpmc in cases where Linux will silently fail and allow rdpmc to return invalid counter values.
This should fix the "attach_cpu_sys_validate" test failure.

don't use fast rdpmc counter reads in attach or syswide scenarios

---

src/sde_lib/sde_lib.c
src/sde_lib/sde_lib.h
src/sde_lib/sde_lib_datastructures.c
src/sde_lib/sde_lib_internal.h
src/sde_lib/sde_lib_misc.c
src/sde_lib/sde_lib_ti.c

This PR fixes the code that unregisters counters in the presence of groups. The basic idea behind the change is adding a reference count to each counter so we can keep track of the number of groups it belongs to. In the process of fixing this, I also abstracted the use of the hash-tables a bit, so we don't access their internal structure from multiple places in the code, and added some locking to prevent race conditions between reading and shutdown.

Sde shutdown

---

src/components/rocm/tests/Makefile

The rocm tests assume hipcc is located under the same root directory as the rest of rocm toolkit software. Spack installs rocm dependencies in separate directories however, which breaks this assumption. This patch introduces a HIP_ROOT variable that, if unset, is set automatically to PAPI_ROCM_ROOT/hip. Spack can use this variable to let the tests Makefile in the PAPI rocm component know where the hipcc compiler is located.

rocm: user HIP_ROOT for hipcc compiler in tests Makefile

---

src/counter_analysis_toolkit/Makefile
src/counter_analysis_toolkit/cat_arch.h
src/counter_analysis_toolkit/flops.c
src/counter_analysis_toolkit/flops.h
src/counter_analysis_toolkit/vec.c
src/counter_analysis_toolkit/vec_scalar_verify.c
src/counter_analysis_toolkit/vec_scalar_verify.h

Re-introduce the GEMM operation in each precision to provide a kernel that executes exclusively fused multiply-add floating-point operations.
These changes have been tested on the AMD Zen4 and Fujitsu A64FX architectures.

cat: put GEMM kernels back in

---

src/components/powercap/linux-powercap.c

This is a bit of a workaround for newer Intel CPUs that, in addition to the traditional "package-<n>" entries in /sys/class/powercap/, also contain a "psys" entry that controls the platform domain (see, e.g., https://lkml.kernel.org/lkml/1458516392-2130-3-git-send-email-srinivas.pandruvada@linux.intel.com/).
PAPI currently assumes that entries starting with "intel-rapl:0" correspond to socket 0 and "intel-rapl:1" to socket 1.  With "psys" around that unfortunately need not be the case; on at least one system relevant to DOE (I can't post the details as it's not public yet) intel-rapl:0 corresponds to socket 0, intel-rapl:1 corresponds to *psys*, and intel-rapl:2 corresponds to socket 1 (what a mess!).  What currently happens is that PAPI entirely misses the counters for socket 1.
This PR …

powercap: ignore the psys entry

---

src/components/rocm/tests/Makefile

Spack has issues building rocm tests because of a broken dependency in hip (openmp). To prevent Spack from failing to build PAPI when the rocm component is enabled, this commit temporarily removes the rocm component tests from being built. A better, and permanent, solution will follow soon.

rocm: temporarely remove all tests from being built

---

src/papi.h

Warnings seen while compiling with gcc 7.5.0
```
/home/anustuv/papidev/papi-AP2/papi/src/install/include/papi.h:1224:4: warning: function declaration isn't a prototype [-Wstrict-prototypes]
int PAPI_rate_stop(); /**< stops a running event set of a rate function */
^~~
/home/anustuv/papidev/papi-AP2/papi/src/install/include/papi.h:1241:4: warning: function declaration isn't a prototype [-Wstrict-prototypes]
int PAPI_hl_stop(); /**< stops a running high-level event set */
^~~
```

papi.h: Fix warnings for -Wstrict-prototypes

---

src/components/cuda/cupti_common.c
src/components/cuda/cupti_common.h
src/components/cuda/cupti_profiler.c

This PR adds the feature that the CUDA component loads the cuda toolkit version that is used by the application.

cuda: Load cuda shared libraries from linked/rpath/LD_LIBRARY_PATH

---

src/components/cuda/cupti_common.c
src/components/cuda/cupti_common.h

Fix link error for gcc >= 10.0

cuda: fix get linked shared library link error gcc 10.0

---

src/components/rocm/rocp.c

Some events have multiple instances. The way the component was handling those events was wrong, causing such events to not work. This patch fixes the problem.

rocm: fix instanced events

---

src/components/cuda/linux-cuda.c
src/papi.h
src/utils/papi_component_avail.c

This commit updates `utils/papi_component_avail` to display cuda component does not support counters.

utils: papi_component_avail does not support cuda component counters

---

src/components/rocm/tests/Makefile
src/components/rocm/tests/hl_intercept_multi_thread_monitoring.cpp
src/components/rocm/tests/hl_intercept_single_thread_monitoring.cpp
src/components/rocm/tests/hl_sample_single_thread_monitoring.cpp
src/components/rocm/tests/multi_thread_monitoring.cpp
src/components/rocm/tests/single_thread_monitoring.cpp

Spack installation of PAPI + rocm component have dependency issues with openmp caused by the AMD llvm compiler. Because component tests are always built in PAPI this prevents spack from installing PAPI in the system. Removing the openmp dependency and replacing with pthreads solves the issue.

rocm: remove openmp dependency from tests

---

src/components/rocm_smi/rocs.c

`ntv_events` might be uninitialised when the error handling section is entered in `init_event_table()`. Make sure that `ntv_events` is always initialised when error handling is performed.

rocm_smi: fix warning "variable might be used uninitialized"

---

src/components/rapl/linux-rapl.c

The `rapl` component currently does not support the Intel Icelake-SP platform as it is missing in the lookup table. I just added the corresponding entry.
Tested on a dual-socket Intel Xeon Gold 6338 system. 
According to the Intel SDM and the Kernel source code, the `PP0` (power consumption of the CPU cores) should be supported on the Icelake architecture. However, on my test system, it is unsupported and does not even show up in `/sys/bus/event_source/devices/power/events/`.  The corresponding MSR is readable but constantly reports zero.
I still suggest setting `pp0_avail=1` for Icelake to be consistent with the kernel.  …

rapl: support for icelake-sp

---

src/components/sysdetect/amd_gpu.c
src/components/sysdetect/nvidia_gpu.c

The `sysdetect` component makes a wrong usage of `snprintf`. In a few instances, `snprintf` is used to copy a string of size X to a string of size `PAPI_MAX_STR_LEN`. However, the `sysdetect` code sets the `n` argument of `snprintf`, indicating the target string length, to the length of the source string (i.e., X). Additionally, sometimes the code null-terminates the target string, which is not necessary because `snprintf` always null-terminates the target string.
_Commits_ have a body (whenever relevant) containing a detailed description of the addressed problem …

Sysdetect: fix snprintf behavior

---

src/components/rocm/rocp.c

The expected return value from snprintf, in the rocm component, is < PAPI_MAX_STR_LEN. If it is >= PAPI_MAX_STR_LEN, the input string was longer than the output string. This PR fixes the rocm component code to align it to the given description.

rocm: fix snprintf handling

---

src/components/coretemp/linux-coretemp.c

This PR fixes 10 warnings generated by gcc 10 of the type
```
components/coretemp/linux-coretemp.c:132:38: warning: '%s' directive output may be truncated writing up to 4095 bytes into a region of size between 3839 and 4094 [-Wformat-truncation=]
132 |      snprintf(path, PATH_MAX, "%s/%s/%s",
|                                      ^~
components/coretemp/linux-coretemp.c:132:6: note: 'snprintf' output 3 or more bytes (assuming 4353) into a destination of size 4096
132 |      snprintf(path, PATH_MAX, "%s/%s/%s",
|      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
133 |        base_dir, hwmonx->d_name,paths[pathnum]);
|        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

coretemp: Fix snprintf warnings for gcc 10

---

src/components/lmsensors/README.md
src/components/lmsensors/linux-lmsensors.c

This behaviour observed on ICL Leconte
```
$ module load lm-sensors
$ export PAPI_LMSENSORS_ROOT=$ICL_LM_SENSORS_ROOT
$ ./configure --with-components="lmsensors" && make && make install
$ utils/papi_component_avail
```
Shows the output
```
...
Name:   lmsensors               Linux LMsensor statistics
\-> Disabled: libsensors.so not found.
```
The problem happens because the component searches for `libsensors.so` in `$PAPI_LMSENSORS_ROOT/lib64` while the so exists in `$PAPI_LMSENSORS_ROOT/lib`
This PR fixes this problem by adding `lib` to the search path for the so file.
After this fix the output of `papi_component_avail` shows
```
...
Name:   lmsensors               lm-sensors provides tools for monitoring the hardware health
...
Name:   lmsensors               lm-sensors provides tools …
```

lmsensors: Add lib/ to explicit search path to .so loader

---

src/components/cuda/linux-cuda.c
src/papi.h
src/utils/papi_component_avail.c

This PR reverts [PR 62: utils: papi_component_avail does not support cuda component counters](https://github.com/icl-utk-edu/papi/pull/62)
This is related to issues
- [cuda component overloads field for utility #71](https://github.com/icl-utk-edu/papi/issues/71)
- [Updated PAPI CUDA component returns default for number of counters #61](https://github.com/icl-utk-edu/papi/issues/61)

cuda: Revert cuda component num_counters not supported by vendor

---

src/smoke_tests/Makefile

Makefile file was missing a PAPI_ROOT path and also an additional -pthread in the linker flags.

smoke_tests: fix Makefile

---

src/configure
src/configure.in

Configure TLS detection tests were failing because of wrong usage of pthread_create(). Problem was caused by wrong definition of thread functions which require void *f(void *) instead of int f(void *) or void f(void *).

configure: fix tls detection

---

.github/workflows/ci.sh
.github/workflows/spack.sh

The upgrade to rocm 5.5/5.7 requires a newer gcc version in the CI.  Updating to gcc@11.

Changing gcc version for rocm compatibility

---

src/components/rocm/roc_profiler.c
src/components/rocm/tests/sample_multi_thread_monitoring.cpp
src/components/rocm/tests/sample_single_thread_monitoring.cpp

Fix rocprofiler issue80: https://github.com/ROCm-Developer-Tools/rocprofiler/issues/80#issuecomment-1725135992.

rocprofiler issue80 fixup

---

src/components/cuda/cupti_profiler.c
src/components/cuda/linux-cuda.c

- Improves overhead from 15000ms to 2200ms for 100 PAPI_read() calls
- Improves speed of `papi_native_avail` utility
- Improvements over old component
- PAPI_start() correctly resets counter values
- Measurements consistent across reads

cuda: Improve CUDA component PAPI_read() overhead, issue 85

---

src/components/cuda/cupti_profiler.c

Before this fix `$ papi_command_line xxxx` causes segfault.
After this fix the segfault is replaced by 
```
This utility lets you add events from the command line interface to see if they work.
Failed adding: xxxx
because: Invalid argument
No events specified!
Try running something like: /home/anustuv/papidev/papi-AP2/papi/src/install/bin/papi_command_line PAPI_TOT_CYC
```
This happens because the cuda component dynamically adds events to its internal structure when `event_name_to_code` is called without checking validity, and returns an event code. Only at `PAPI_start` it complains if the event cannot be added to the lower layers.
Enumeration of all cuda events is a heavy operation and thus it does not do it unless explicitly requested.

cuda: Fix papi_command_line segfault when passed non-existent event name

---

src/configure
src/configure.in
src/sde_lib/Makefile

Only build PAPI with debug symbols if `--with-debug=(yes|mem)` is set.
Addresses issue #92 

Do not build PAPI and SDE lib with debug symbols by default

---

src/components/rocm/README.md

For versions of ROCM >= 5.2.0, the ROCM library path structure is different.
The README has been updated to reflect this difference.
This was verified on the Frontier supercomputer.

rocm: update README

---

src/components/coretemp/linux-coretemp.c
src/components/net/linux-net.c
src/components/sysdetect/linux_cpu_utils.c
src/ctests/thrspecific.c

I reviewed coverity scan results for papi. There were a number of
areas flagged by coverity. This pull request addresses a small
portion of them. Specifically it addresses:
ctests/thrspecific.c: cleaning up allocated memory
sysdetect: properly closing file on all paths through code
linux-net: ensuring that strings are properly terminated
coretemp: ensuring that strings are properly terminated
coretemp: properly closing file on all paths through code
The commits are self contained and only do one thing for each commit. The also contain a description of what each commit is doing. However, the headers do not precisely follow the format of 'module: short description'.
I ran the tests for both the master git branch and this branch. I did not see any differences in the results.
_Why_ this PR …

Fixes for coverity reported issues in various files (redo of pull#46)

---

src/components/rocm/roc_profiler.c

This PR includes a set of minor fixes for the rocm component. These include the removal of `assert` statements, which are replaced by proper error handling logic.

Minor fixes for ROCm component

---

.github/workflows/ci.sh
src/configure
src/configure.in

The --enable-warnings configure flag allows for a maintainer build where the compiler (gcc) uses -Wall -Wextra.

configure: add --enable-warnings flag

---

src/components/rocm/roc_profiler.c

The intercept mode path keeps track of events of intercepted kernel using the same hash table used to map event names to entries in the native event table (hash table normally used to do `ntv_name_to_code` conversions). The event names in the hash table don't collide because intercept mode keeps track of the base name of the event (discarding device and instance number), while native event table entries are referenced through `name:device=N:instance=M` keys. 
The reason for storing only the name of the event in intercept mode is that events are set up on all devices' dispatch queues, regardless the device specified by the user (this approach follows `rocprof` strategy). However, using only the event name without the instance number will cause problems. Instances represent separate events …

rocm: fix bug in intercept mode path

---

src/utils/Makefile

When the sde component is initialized, in the context of an application that uses PAPI, it looks for the availability of libsde symbols. The rationale is that if the application is not linked against libsde, there are no SDEs to read, so the component disables itself. Therefore, papi_component_avail, which does not export any SDEs itself, always reported the sde component as "Disabled". Adding the symbols to the utility resolves this problem.
The …

utils: Fix bogus "Disabled" message in papi_component_avail for the sde component.

---

src/counter_analysis_toolkit/dcache.c
src/counter_analysis_toolkit/dcache.h

Add information about the cache sizes in the header of the output file.

---

src/components/rocm/README.md

rocm: add known problems with some events to README

---

src/components/sysdetect/tests/Makefile

sysdetect: add -ffree-form to silence error in ARM comp

---

src/components/template/README.md
src/components/template/Rules.template
src/components/template/template.c
src/components/template/tests/Makefile
src/components/template/tests/simple.c
src/components/template/vendor_common.c
src/components/template/vendor_common.h
src/components/template/vendor_config.h
src/components/template/vendor_dispatch.c
src/components/template/vendor_dispatch.h
src/components/template/vendor_profiler_v1.c
src/components/template/vendor_profiler_v1.h

This PR adds a more complex example of component design that focuses on component extendability. This component also showcases a simple example of qualifier support through the `TEMPLATE_FUNCTION` event that supports exponential and linear functions. Powers of 2 are returned at every call of `PAPI_read` when the exponential function is selected by the user. Incremental values from 1 onwards are returned at every call of `PAPI_read` when the linear function is selected.
```
$ utils/papi_component_avail
Available components and hardware information.
PAPI version             : 7.0.1.0
Operating system         : Linux 6.1.62-1.el9.elrepo.x86_64
Model string and …
```

template: add template for new components

---

src/components/rocm/roc_common.c
src/components/rocm/roc_common.h
src/components/rocm/roc_dispatch.c
src/components/rocm/roc_dispatch.h
src/components/rocm/roc_profiler.c
src/components/rocm/roc_profiler.h
src/components/rocm/roc_profiler_config.h
src/components/rocm/rocm.c
src/components/rocm/tests/Makefile

This PR introduces event qualifier support in the ROCm component.
Also, solves issue #100
Main changes introduced by this PR are for `papi_component_avail`, that now shows a significantly smaller number of ROCm component events (these are the unique event names without any `:device=` or `:instance=` addition to the name) and `papi_native_avail`, that now shows `:device=` and `:instance=` as event qualifiers. Following an example for a system with two AMD GPUs:
```
$ utils/papi_component_avail
Available components and hardware information.
PAPI version             : 7.0.1.0
Operating system         : Linux 6.1.62-1.el9.elrepo.x86_64
Model string and code    : …
```

ROCm event id refactor

---

.github/workflows/ci.sh
.github/workflows/main.yml

Tests should make sure real use cases work as expected. Some tests might not working correctly if -O0 is used as optimization level in the compiler. For example, the ROCm runtime submits a kernel of 4 waves if the tests are built using -O0, which makes the tests fail.

ci: run tests with and without PAPI debug enabled

---

src/configure
src/configure.in

Thread start routines must return a `void *` value, and future compilers refuse to convert integers to pointers with just a warning (the `virtualtimer` probe).  Without this change, the probe always fails to compile with future compilers (such as GCC 14).
For the `tls` probe, return a null pointer for future-proofing, although current and upcoming C compilers do not treat this omission as an error.
Updates commit dd11311aadbd06ab6c76d ("configure: fix tls detection").
Related to:
* https://fedoraproject.org/wiki/Changes/PortingToModernC
* https://fedoraproject.org/wiki/Toolchain/PortingToModernC
_Commits_ have a header of the …

configure: Fix return values in start thread routines

---

src/components/rocm/roc_profiler.c

The ROCm component `ntv_code_to_info` function does not behave consistently with other components (e.g., `perf_event`). This PR fixes the function behavior to align it to the CPU component.

Minor fixes for ROCm component qualifiers

---

src/components/cuda/cupti_common.c
src/components/cuda/cupti_common.h
src/components/cuda/cupti_profiler.c

The cuda component init function now returns the proper cuda error message for the `disabled_reason` string. This allows PAPI users to pin point more precisely what went wrong with the component initialization. 
Example of system not properly configured:
```
$ utils/papi_component_avail
Available components and hardware information.
PAPI version             : 7.0.1.0
Operating system         : Linux 6.1.62-1.el9.elrepo.x86_64
Model string and code    : AMD EPYC 7742 64-Core Processor (49, 0x31)
CPU revision             : 0.000000
CPUID                    : Family/Model/Stepping 23/49/0, 0x17/0x31/0x00
CPU Max MHz              : 2250
CPU Min MHz              : …
```

Cuda component init error handling

---

src/components/rocm/tests/Makefile
src/components/rocm/tests/hl_intercept_multi_thread_monitoring.cpp
src/components/rocm/tests/hl_intercept_single_kernel_monitoring.cpp
src/components/rocm/tests/hl_intercept_single_thread_monitoring.cpp
src/components/rocm/tests/hl_sample_single_kernel_monitoring.cpp
src/components/rocm/tests/hl_sample_single_thread_monitoring.cpp
src/components/rocm/tests/matmul.cpp
src/configure
src/configure.in

ROCm 6.0.0 causes the build process to fail with an error due to a bug in the rocm_smi header. The sysdetect component is always built by default in PAPI and it uses the rocm_smi headers when these are available through the PAPI_ROCM_ROOT environment variable. This PR isolates the problem to the rocm_smi component by looking for the headers in PAPI_ROCMSMI_ROOT instead. The reason PAPI_ROCM_ROOT was used previously is that the rocm_smi headers are normally installed under the same rocm installation directory as other packages (e.g. HSA and Rocprofiler).
_Commits_ …

Fix for ROCm SMI

---

src/counter_analysis_toolkit/flops.c

On some older versions of GCC (10.3.0), not having at least a 'break' in a switch-case statement can yield the compiler warning: "label at end of compound statement"
These changes fix this error and have been tested on the AMD Zen3 architecture.

cat: fix compile-time error

---

src/components/sysdetect/tests/Makefile

To fix ARM compiler builds, #108 added these lines to the `Makefile` for `sysdetect` tests:
```diff
+ FFLAGS += -ffree-form
+
ifeq ($(notdir $(F77)),gfortran)
FFLAGS +=-ffree-form -ffree-line-length-none
else ifeq ($(notdir $(F77)),flang)
FFLAGS +=-ffree-form
else ifneq ($(findstring $(notdir $(F77)), $(intel_compilers)),)
FFLAGS +=-free
else ifneq ($(findstring $(notdir $(F77)), $(cray_compilers)),)
FFLAGS +=-ffree
endif
```
but this adds `-ffree-form` to every compiler. This breaks [cray compiler builds for PAPI 7.1.0](https://gitlab.spack.io/spack/spack/-/jobs/9684882):
```
1307    /home/gitlab-runner-protected-3/builds/Cj9btwqn/0/spack/spack/lib/
spack/env/cce/ftn -ffree-form -ffree -I../../.. -o query_device_si
mple_f query_device_simple_f.F ../../../libpapi.a
1308    ftn-78 ftn: …
```

sysdetect: fix bug where Makefile sets `-ffree-form` everywhere

---

src/linux-context.h
src/linux-timer.c
src/mb.h

This adds basic support for the RISC-V architecture
After this PAPI will compile and the tools will run, however no events will work because of missing libpfm4 support.
Tested on a BeagleV-Ahead board

add initial riscv support

---

src/components/appio/README.md
src/components/bgpm/README.md
src/components/coretemp/README.md
src/components/coretemp_freebsd/README.md
src/components/cuda/README.md
src/components/emon/README.md
src/components/example/README.md
src/components/host_micpower/README.md
src/components/infiniband/README.md
src/components/io/README.md
src/components/libmsr/README.md
src/components/lmsensors/README.md
src/components/lustre/README.md
src/components/micpower/README.md
src/components/mx/README.md
src/components/net/README.md
src/components/nvml/README.md
src/components/pcp/README.md
src/components/perf_event/README.md
src/components/perf_event_uncore/README.md
src/components/powercap/README.md
src/components/powercap_ppc/README.md
src/components/rapl/README.md
src/components/rocm/README.md
src/components/rocm_smi/README.md
src/components/sde/README.md
src/components/sensors_ppc/README.md
src/components/stealtime/README.md
src/components/sysdetect/README.md
src/components/vmware/README.md

Update the README markdown header links for each component listed within the following [table](https://github.com/icl-utk-edu/papi/wiki/PAPI-Overview#list-of-components). The original header links within each README, were dead links and therefore selecting one resulted in not jumping to the desired section. This was caused by using the following syntax _(#markdown-header-name-of-section)_. Simply removing _#markdown-header_ fixes this issue. 
Tested on Guyot, by previewing and selecting updated markdown header links. Each updated README had the correct behavior of jumping to the correct section that was selected.
_Commits_ have …

Updates to Individual Component README's to Fix Markdown Links

---

src/papi_fwrappers.c

This PR updates the PAPI Fortran wrappers for: `PAPIF_flops_rate`, `PAPIF_flips_rate`, and `PAPIF_epc`.  All three of the aforementioned functions had a first argument of `int event`. However, setting `int event` equal to events such as `PAPI_FP_OPS` for `PAPIF_flops_rate`,  `PAPI_FP_INS` for `PAPIF_flips_rate`, and `PAPI_TOT_INS` for `PAPIF_epc` would result in an error being output, specifically -7. Which means the "Hardware event does not exist". This is not the correct behavior due to the events existing and the associated C low-level functions running correctly given the same input. 
To fix this issue, `int event` was changed to `int *EventCode` for `PAPIF_flops_rate`, `PAPIF_flips_rate`, and `PAPIF_epc`. As well as `*EventCode` being passed to the C function calls within the …

Update to Arguments for PAPIF_flops_rate, PAPIF_flips_rate, PAPIF_epc

---

src/high-level/scripts/papi_hl_output_writer.py

This PR adds an additional flag to `papi_hl_output_writer.py` titled `source_file`. This allows a user the flexibility to pass either a directory such as `papi_hl_output` which contains one or more `.json` files or a single `.json` file such as `rank_082041.json`. 
A few examples will be outlined below.
- Case 1: Passing an individual file to `papi_hl_output_writer.py`:
```
python3 papi_hl_output_writer.py --source_file rank_082041.json --notation=derived --type=summary
{
"computation": {
"Region count": 1,
"Real time in s": 0.0,
"IPC": 0.43
}
}
```
- Case 2: Error handling if a user passes an individual file and a directory to `papi_hl_output_writer.py`:
```
python3 papi_hl_output_writer.py --source papi_hl_output --source_file papi_hl_output/rank_082041.json --notation=derived …
```

Adding support for optional individual file flag to papi_hl_output_writer.py

---

src/counter_analysis_toolkit/Makefile

The CAT Makefile originally used `${HOME}/usr` as the path to link to files such as `papi.h`. However, if a users environment is not setup properly this path will not find the correct files such as `papi.h`. 
Instead of `${HOME}/usr` to be searched, the environment variable `PAPI_DIR` will now be used. This mirrors what the documentation suggests to do after a user installs PAPI. See 4. at the following [link](https://github.com/icl-utk-edu/papi/wiki/Downloading-and-Installing-PAPI).
Tested by running `make` within the `counter_analysis_toolkit` directory on Guyot and subsequently running `./cat_collect -in event_list.txt -out OUT_DIR -branch`. With `event_list.txt` containing `PAPI_TOT_INS 0`. Output can be seen below:
```
81.50
81.00
78.00
596.25
730.50
730.00
336.50
469.00
469.75 …
```

Updating CAT Makefile to use PAPI_DIR Enviornment Variable

---

src/utils/papi_avail.c

Within `papi_avail.c` there is currently a small bug that occurs when passing `--mem` as the command line option. For example if you run `./papi_avail --mem` the output currently is: 
```bash
Available PAPI preset and user defined events plus hardware information.
PAPI version             : 7.1.0.0
Operating system         : Linux 6.1.62-1.el9.elrepo.x86_64
Model string and code    : AMD EPYC 7742 64-Core Processor (49, 0x31)
CPU revision             : 0.000000
CPUID                    : Family/Model/Stepping 23/49/0, 0x17/0x31/0x00
CPU Max MHz              : 2250
CPU Min MHz              : 1500
Total cores              : 256
SMT threads per core     : 2
Cores …
```

Bug fix to correct behavior of --mem command line option for papi_avail.c

---

src/sde_lib/Makefile

A recent annocheck of the papi RPMS showed that libsde.so.1.0 was not built with the expected flags passed into the RPM build.  Minor changes were made to src/sde_lib/Makefile to use the CFLAGS and LDFLAGS passed in.
This is a revision of pull request #182 based on the discussion.
- [ x] **Description**
- [ x] **Commits**
- [ x] **Tests**

SDE_LIB: Build libsde.so.1.0 with the CFLAGS and LDFLAGS passed in

---

src/utils/papi_avail.c

This PR addresses updating a conditional check within `papi_avail.c` such that when passing either `--cache` or `--cnd` on the command line we do not accidentally enter. Which would result in output being incorrect. Please see Issue #183 for more details/output.

Updating Conditional Check to Avoid Accidentally Entering with --cache and --cnd for papi_avail.c

---

src/components/sysdetect/linux_cpu_utils.c
src/linux-memory.c

Dear @gcongiu , @adanalis 
Dear papi library development team,
There was a bug in the buffer overflow fix below.
Use fgets in place of fscanf functions to avoid possible buffer overflows
https://github.com/icl-utk-edu/papi/commit/ec2aa022fee2a1d0decf1d5b2e7e28a4ca2cf794
The buffer overflow fix rewrites fscanf() to fgets(), 
but there is a difference in the specifications between fscanf() and fgets(): 
in fscanf(), "\n" is not read, but in fgets(), "\n" is also read, 
so it seems necessary to remove the unnecessary "\n" to do the same.
For this reason, generic_get_memory_info() could not obtain cache information 
strings from allocation_policy, type, and write_policy under 
the /sys/devices/system/cpu/cpu0/cache/index[012] directory as expected.
The buffer overflow update fix allows us to …

Update:Use fgets in place of fscanf functions to avoid possible buffer overflows

---

src/papi.c

Pull requests updates `PAPI_enum_event(int * EventCode, int  modifer)` to: 
1. Update documentation to show modifiers that are allowed to be passed by a user
2. Add conditional check to make sure a valid modifier is provided
No internal code utilizes the ITANIUM/Power modifiers. Checked with Github's search functionality.

Update Allowed Modifiers for PAPI_enum_event 

---

src/libpfm4/lib/events/intel_adl_grt_events.h

Current with
commit 4bdeb7e067363013257460bdb6c3dbae778b5634
Author: Stephane Eranian <eranian@gmail.com>
Date:   Fri Jun 14 22:14:05 2024 -0700
Fix encoding of inst_retired.* on Alderlake E-core
Was returning event code 0x0 for both .any and .any_p umasks.
any_p refers to the generic counter encoding which uses event
code 0xc0.
Signed-off-by: Stephane Eranian <eranian@gmail.com>
Note: Unable to test due to the PAPI team not having access to a machine with Alderlake as of now.
_Commits_ have a body (whenever relevant) containing a detailed description of the …

Update libpfm4 to commit 8b5634

---

src/papi.c

Unlike for `PAPI_read()` and `PAPI_stop()` where the `values` array is only initialized (written) in these functions. `PAPI_accum()` must have the `values` array initialized, because its values are read in.
Due to not being able to check to see if the `values` array is initialized, we will document in the Doxygen that the `values` array must be initialized.
Programmer's Manual User Perspective (Doxygen):

Add Note in Doxygen Regarding Values Array in PAPI_accum() 

---

src/components/perf_event/pe_libpfm4_events.c
src/papi_internal.c

Initial support for Intel alderlake and raptorlake heterogeneous CPUs that have both e-cores and p-cores.  This makes it so PAPI can build, run, and enumerate native events on these systems.  (Without these patches PAPI won't run at all, it will just give an error).
We are still working on validating the results gathered by PAPI on these systems.

perf_event: initial heterogeneous CPU support

---

src/components/rocm/roc_dispatch.c
src/components/rocm/roc_dispatch.h
src/components/rocm/roc_profiler.c
src/components/rocm/roc_profiler.h
src/components/rocm/rocm.c

These changes address Issue #203.
The event count previously only counted basenames. This has been changed to include all qualified event names.
These changes have been tested on the Frontier supercomputer (AMD MI250X GPU architecture) with ROCm version 5.3.0.

rocm: fix event count to include qualifiers

---

src/components/cuda/tests/Makefile

If CUDA tests are linked with the PAPI shared library (`.so`) (configure option `--with-shlib-tools`), the tests don't build because `nvcc` doesn't accept the `-Wl,-rpath` linker option.
To fix this issue, instead of linking with `nvcc`, we can link with the PAPI-chosen C compiler via the `CC` macro (or `CXX` macro for tests with C++ code).
Additionally, this PR cleans up other issues with tests (e.g., `cudaOpenMP.cu` and `cudaOpenMP_noCuCtx.cu`) by removing redundant explicit compilations, as the Makefile already includes a compilation rule. 
(Fixes #205, second part)
_Commits_ have a header of the form: `module: short …

Fixed issue with building CUDA tests when linked with shared PAPI lib

---

src/components/cuda/linux-cuda.c
src/components/cuda/tests/Makefile

When working through and trying to build locally build a PAPI RPM with the cuda component enabled, I found a couple minor issues in the cuda component that prevented it from being built:
1. An sprintf without a format string 
2. Assumption that nvcc would be on the default path
When runing "run_tests.sh" the ctests/all_native_events: took a number of hours to complete, but the tests eventually completed.

Cuda component fixes

---

src/components/cuda/README.md

Updates the Cuda component README to prepend necessary libraries to `LD_LIBRARY_PATH` instead of appending.
From:
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PAPI_CUDA_ROOT/lib64
```
To:
```
export LD_LIBRARY_PATH=$PAPI_CUDA_ROOT/lib64:$LD_LIBRARY_PATH
```

Updating format of export LD_LIBRARY_PATH= in Cuda component README

---

src/components/rocm/roc_dispatch.c
src/components/rocm/roc_dispatch.h
src/components/rocm/roc_profiler.c
src/components/rocm/roc_profiler.h
src/components/rocm/rocm.c

This PR makes it such that only the base event names for a component will be count in output from `papi_component_avail` and `papi_native_avail`. Therefore, PR #204 is reverted to the original way the counting was done for `papi_component_avail`.
As of the PICL meeting on August 1st, 2024 it was discussed to only count base event names due to the complexity of getting the correct count. Reasons for this decision are:
1. A component such as `perf_event` could have an event with multiple combinations of qualifiers; therefore, getting the correct total event count would be difficult. 
2. As stands, we can accurately count base event names for both `papi_component_avail` and `papi_native_avail`. With the output matching between the two. 
```
[trebu@login04.frontier bin]$ srun --account=CSC617 …
```

For papi_component_avail Count Only Base Event Names

---

src/components/rocp_sdk/Rules.rocp_sdk
src/components/rocp_sdk/rocp_sdk.c
src/components/rocp_sdk/sdk_class.cpp
src/components/rocp_sdk/sdk_class.h
src/components/rocp_sdk/sdk_class.hpp
src/components/rocp_sdk/tests/Makefile
src/components/rocp_sdk/tests/advanced.c
src/components/rocp_sdk/tests/kernel.cpp
src/components/rocp_sdk/tests/simple.c
src/configure
src/configure.in

This component offers early support for AMD GPU/APU events through the new ROCprofiler-SDK library. Due to limitations in the vendor library, the component has the following limitations:
A) Only the dispatch mode is currently supported, which means that events can only be read after a kernel has completed, not during the execution of the kernel.
B) Event dimensions, such as "instance", or "shader_engine" are currently aggregated and can't be accessed individually.

Beta support for AMD ROCprofiler-SDK events.

---

.github/workflows/spack.sh

This temporarily fixes the version on cuda using the spack installation test to version 12.5.1 which is the currently highest version that works with papi.

Temporary fix for cuda version in CI

---

src/components/cuda/README.md

Corrected the name of the 'papi_native_avail' utility.

cuda: fix typo in README

---

src/components/cuda/tests/Makefile

This PR removes the conditional block which determined if the `-arch=native` flag was used. There is no apparent difference to setting this flag or not.  See below for test output after removal of the conditional block.
Command line:
```
./simpleMultiGPU cuda:::dram__bytes.avg
```
Output:
```
Starting simpleMultiGPU
PAPI version: 7.1.0
CUDA-capable device count: 8
CUDA Device 0: Tesla V100-SXM2-32GB : computeCapability 7.0 runtimeVersion 12.1 driverVersion 12.5
CUDA Device 1: Tesla V100-SXM2-32GB : computeCapability 7.0 runtimeVersion 12.1 driverVersion 12.5
CUDA Device 2: Tesla V100-SXM2-32GB : computeCapability 7.0 runtimeVersion 12.1 driverVersion 12.5
CUDA Device 3: Tesla V100-SXM2-32GB : computeCapability 7.0 runtimeVersion 12.1 driverVersion 12.5
CUDA Device 4: Tesla V100-SXM2-32GB …
```

Removing conditional check for -arch=native flag.

---

src/run_tests.sh

Full Test only active components. In the run_tests.sh script, when checking for components tests filter for active/inactive components.
When the only active components are `perf_event, perf_event_uncore, and sysdetect`.
Command line:
`make fulltest`
```
The following test cases will be run:
validation_tests/cycles_validation validation_tests/flops_validation validation_tests/fp_validation_hl validation_tests/papi_br_cn validation_tests/papi_br_ins validation_tests/papi_br_msp validation_tests/papi_br_ntk validation_tests/papi_br_prc validation_tests/papi_br_tkn validation_tests/papi_br_ucn validation_tests/papi_dp_ops validation_tests/papi_fp_ops validation_tests/papi_hw_int validation_tests/papi_l1_dca validation_tests/papi_l1_dcm validation_tests/papi_l2_dca validation_tests/papi_l2_dcm …
```

 run_tests.sh: Full Test only active components

---

src/libpfm4/README
src/libpfm4/docs/Makefile
src/libpfm4/docs/man3/libpfm_arm_ac72.3
src/libpfm4/include/perfmon/pfmlib.h
src/libpfm4/lib/events/intel_gnr_events.h
src/libpfm4/lib/pfmlib_arm.c
src/libpfm4/lib/pfmlib_arm_armv8.c
src/libpfm4/lib/pfmlib_common.c
src/libpfm4/lib/pfmlib_priv.h
src/libpfm4/tests/validate_x86.c

Current with
commit 9c5c88e734e866f0801b80c527330ad6dbe21e89
Author: Stephane Eranian <eranian@gmail.com>
Date:   Tue Sep 10 23:58:35 2024 -0700
add ARM Cortex A72 Core PMU support
As a clone of Cortex A57.
Signed-off-by: Stephane Eranian <eranian@gmail.com>
commit 6d276b48eba5ead4e3fd4b6eca359504f2b69b6c
Author: Ian Rogers <irogers@google.com>
Date:   Mon Sep 9 09:22:50 2024 -0700
fix pfm_arm_detect() buffer initialization problem
Commit 3abda5bc6c1a ("Optimize pfm_detect() for ARM processors")
added an optimization to avoid parsing /proc/cpuinfo too many times.
But it had a bug whereby it was reinitializing the pfm_arm_cfg.*
fields multiple times and potentially from an uninitialized buffer.
Signed-off-by: Ian Rogers <irogers@google.com>
commit fd3191c34ad87e22d3f3d31d2cf5c1050a9136ba …

Update libpfm4 to Commit e21e89

---

src/components/rocp_sdk/sdk_class.cpp
src/components/rocp_sdk/sdk_class.hpp
src/components/rocp_sdk/tests/Makefile
src/components/rocp_sdk/tests/kernel.cpp
src/components/rocp_sdk/tests/two_eventsets.c

Create the dispatch profile when the user calls PAPI_start(), not when the dispatch callback is invoked.
Create as many profiles as there are devices requested by the user events, and associate each profile with the corresponding agent.

Better support for multiple eventsets and multiple devices.

---

src/libpfm4/lib/pfmlib_common.c
src/libpfm4/lib/pfmlib_priv.h

Current with
commit 0118612a28d270e78d1f17c24e9db0935e332285
Author: Stephane Eranian <eranian@gmail.com>
Date:   Tue Sep 17 16:36:24 2024 -0700
remove extraneous printf in pfmlib_init_env()
Was introduced by mistake by commit:
32b7c3d6ab6b ("add LIBPFM_PROC_CPUINFO variable for Linux")
Signed-off-by: Stephane Eranian <eranian@gmail.com>
Current with
commit 3724e7ef87e71dd1de46ef4eb4ec2b1be4ea63e5
Author: Stephane Eranian <eranian@gmail.com>
Date:   Sun Sep 15 22:29:37 2024 -0700
add LIBPFM_PROC_CPUINFO variable for Linux
Allows overriding the filename used to parse the /proc/cpuinfo
file. This can be used to detect certain CPU models, such
as on ARM. Providing an override allows testing without the actual
hardware.
Signed-off-by: Stephane Eranian <eranian@gmail.com>
Note: Built PAPI on …

Update libpfm4 to Commit 332285

---

src/components/rocm/rocm.c

This PR updates the disabled reason in the ROCm component to be an empty string if the component has properly been initialized. Previously, the string for disabled reason would show: `Not initialized. Access component events to initialize it.` regardless of being initialized or not. 
```
Disabled Reason: Not initialized. Access component events to initialize it.
```
```
Disabled Reason: 
```

Update ROCm Component Disabled Reason if Initialized

---

src/components/rocm_smi/rocs.c

Derived events are handled in the `handle_special_events` function. This name is not intuitive. Use the more descriptive `handle_derived_events` instead.

rocm_smi: rename special cases to derived events

---

src/papi.c

This PR updates the `PAPI_add_named_event` documentation. Specifically updating the list of params.
As stands the documentation is the following:
``` 
@params EventCode
A defined event such as PAPI_TOT_INS.
```
The update would see the above changed to:
```
@params EventName
A string containing the event name as listed in papi_avail or papi_native_avail.
```
Merging this PR will close Issue #2.

Correcting documentation in PAPI_add_named_event

---

src/components/intel_gpu/internal/inc/GPUMetricInterface.h
src/components/intel_gpu/internal/src/GPUMetricHandler.cpp
src/components/intel_gpu/linux_intel_gpu_metrics.c

This PR addresses bugs that were present in the intel_gpu component, namely:
- Fix mapping between the metric code and metric group ID.
- Remove check preventing metrics from separate groups from being added to separate event sets.
- Implement PAPI_cleanup_eventset() functionality.
This Pull Request addresses Issue #227.
These changes have been tested using an OpenCL matrix addition kernel on the Intel Ponte Vecchio architecture.
The PR needs to …

2024.09.18 intel_gpu bug fixes

---

src/high-level/scripts/papi_hl_output_writer.py

Python3 has been released for over 15 years.  Fedora, Debian, and other distributions state that python scripts should avoid using unversioned python intepreter:
https://fedoraproject.org/wiki/FinalizingFedoraSwitchtoPython3 https://www.debian.org/doc/packaging-manuals/python-policy/
The RPM build process will flag unversioned python interpreter use as an error and the build will fail.  Making the papi_hl_output_writer.py explicitly use /usr/bin/python3.
_Commits_ have a body (whenever relevant) containing a detailed description of the addressed problem and its …

high-level: Explicitly use python3

---

src/linux-memory.c

Support for ARM Neoverse V2 and bug fixes.
These changes have been tested on the ARM Neoverse V2, ARM Cortex-A72, and AMD Zen3 architectures.

2024.02.15 Updates to papi_mem_info

---

src/run_tests.sh

Change paths from libpfm-3.y to libpfm4 so that the tests link to libpfm.so.4
This Pull Request addresses Issue #240.
These changes have been tested on the NVIDIA Grace-Hopper architecture.

run_tests.sh: change libpfm-3.y to libpfm4

---

src/Makefile.in

In `Makefile.in` the PAPI version was still set to 7.1.0.0, which meant the library file names at the location `papi-install/lib` would read `libpapi.so.7.1` and `libpapi.so.7.1.0.0`.  This PR updates `Makefile.in` to account for the current version of PAPI: 7.2.0.0b1. 
Updating `Makefile.in` with the current version of PAPI will see the library file names updated to:
```
libpapi.so.7.2
libpapi.so.7.2.0.0b1
```

Update Makefile.in to have PAPI version 7.2.0.0b1.

---

src/counter_analysis_toolkit/Makefile

When compiling the Counter Analysis Toolkit (CAT) if the wrong architecture is selected for the ARCH variable, relatively confusing compilation errors can occur. For example, compiling on an ARM machine with the default `ARCH=X86` setting produces the following GCC error: `gcc: error: unrecognized command-line option ‘-mfma’`.
To prevent this from happening, make the CAT Makefile use 'uname -m' to detect if the architecture is arm or x86, and otherwise assume powerpc. If ARCH is already set, leave it alone. This change streamlines the workflow of using the CAT on new devices.
_Commits_ have a header of the form: `module: short …

counter_analysis_toolkit: Automatically detect platform in Makefile

---

src/components/cuda/cupti_profiler.c
src/components/cuda/papi_cupti_common.c

This PR updates the ordering of conditional checks in the Cuda component. Specifically for the functions `load_cudart_sym`,`load_cupti_common_sym`,  and `load_nvpw_sym`. 
Current master has the following workflow of checks:
1. Check to see if  `PAPI_CUDA_RUNTIME`/`PAPI_CUDA_CUPTI`/`PAPI_CUDA_PERFWORKS` are set, if so we will search this path for the necessary library files.
2. Use `dl_iterate_phdr()` to walk through the list of shared objects linked in the executable.
3. Check to see if `PAPI_CUDA_ROOT` is set and the previous two steps failed; we then search the path that `PAPI_CUDA_ROOT` is set to for the necessary library files. 
4. We use `dlopen`.
This PR updates the workflow of checks to:
1. Check to see if  `PAPI_CUDA_RUNTIME`/`PAPI_CUDA_CUPTI`/`PAPI_CUDA_PERFWORKS` are set, if so …

Updating the order of conditional checks to load library files in the Cuda component

---

src/components/cuda/cupti_profiler.c

This pull request will allow a user to supply just the base Cuda native event name to a PAPI function call and we internally will handle it as if `:device=0` was supplied. Therefore, a user supplying just `cuda:::dram__bytes.avg` will not encounter the error `PAPI_ENOEVNT` anymore. 
Code:
```c
#include "papi.h"
#include <cuda.h>
#include <stdio.h>
#include <stdlib.h>
int main() {
int retval, EventCode, EventSet = PAPI_NULL, Events, number = 1;
char EventName[PAPI_MAX_STR_LEN];
long long values[1]; 
CUcontext pctx;
CUresult status = cuInit(0);
if (status != CUDA_SUCCESS) {
printf("Failed to create context: %d\n", status);
}   
retval = PAPI_library_init(PAPI_VER_CURRENT);
if (retval != PAPI_VER_CURRENT) {
printf("Failed to initialize PAPI.\n");
exit(1);
} 
retval = …
```

Allow for a user to supply just the base cuda native event name

---

gitlog2changelog.py
release_procedure.txt

This PR addresses resolving Issue #232.
- Added command line arguments
- Correctly take into account the `re.search` return value
- Fixed bug that would cause the final `git log` entry to not be stored
- Updated Bitbucket workflow for GitHub workflow
- Added an additional section for how to do a GitHub release
- Restructured text and code examples

Update gitlog2changelog.py and release_procedures.txt

---

src/components/cuda/tests/Makefile

In GLIBC version 2.34, libpthread as a separate library has been removed. Most components that used to be in a separate shared object have been placed into the main libc object, `libc.so.6`. Due to this, the `-lpthread` flag is not needed in GLIBC >= 2.34. See the following [webpage ](https://developers.redhat.com/articles/2021/12/17/why-glibc-234-removed-libpthread#) for more discussion on this topic. 
Even with versions of GLIBC >= 2.34 or GLIBC < 2.34, we still should place the `-pthread` flag when needed. `-pthread` encompasses `-lpthread`, but it also defines extra macros. From the man pages for gcc the following is stated for the `-pthread` flag: You should use this option consistently for both compilation and linking.
_Why_ this PR exists. Reference all relevant information, …

Updating Cuda Tests Makefile with -pthread

---

src/papi_events.csv

The previous definition counted floating-point instructions instead of operations. Added note to papi_events.csv that explains how to scale and combine native events to measure all FLOPs with multiplexing.
These changes have been tested on the IBM POWER9 and POWER10 architectures.

presets: remove PAPI_FP_OPS from POWER9 & POWER10

---

src/components/cuda/tests/Makefile

The Makefile for CUDA component tests includes the line PAPILIB += -L../../../libpfm4/lib -lpfm for linking, but this linkage is unnecessary and causes errors when the perf_event and perf_event_uncore components are disabled because libpfm4 is not built.

cuda/test/Makefile: Remove unecessary linking for cuda 

---

src/components/rapl/linux-rapl.c

This PR adds support for the `rapl` component on Intel's RaptorLake architecture. Adding this was extremely simple as RaptorLake has the same RAPL setup as SandyBridge and IvyBridge.
Tested systems:
| **System Name** | **Family/Model/Stepping** | `papi_native_avail` | `papi_component_avail` | `papi_command_line` | **RAPL tests** |
|-------------|-----------------------|-------------------|----------------------|-------------------|------------|
| Raptor Lake-S/HX B0  | 0x6/0xb7/0x1 |<ul><li> [x] </li></ul>|<ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> |<ul><li> [x] </li></ul>|
_Commits_ have a header of the form: `module: …

rapl: Added RAPL component support for Intel RaptorLake.

---

src/ctests/all_native_events.c
src/ctests/get_event_component.c

This PR looks to add an optional flag to `all_native_events.c` and `get_event_component.c` titled `--disable-cuda-events` with options of `yes` and `no` (the default is no). The reason for this is due to the runtime length of `all_native_events.c` and `get_event_component.c`when the Cuda component has been compiled in.
Along with the `--disable-cuda-events` option, I have also added `-h` and `--help`. Example of `--help` and `-h` is below (shown is `all_native_events.c`, but similarly is `get_event_component.c`):
```
This is the all_native_events program.
For all components compiled in, it attempts to: add the component events, start, and stop.
Usage: ./all_native_events [options]
General command options:
-h, --help                           Print the help message. …
```

Update all_native_events.c and get_event_component.c to allow users to optionally disable Cuda native events

---

src/components/rapl/linux-rapl.c

This PR will add support for AMD Family 25 (19h) in the RAPL component. As a result of this, Issue #141 will be resolved. See commit message or below for Zen 3/Zen 4 model's tested. 
| System Name  | Family/Model/Stepping |  `papi_native_avail`  | `papi_component_avail` | `papi_command_line`  | RAPL tests |
| :-------------: | :-------------: | :-------------: | :-------------: | :-------------: | :-------------:|
| Gilgamesh  | 25/1/1  | ✅   | ✅ | ✅  | ✅   |
| System Name  | Family/Model/Stepping |  `papi_native_avail`  | `papi_component_avail` | `papi_command_line`  | RAPL tests |
| :-------------: | :-------------: | :-------------: | :-------------: | :-------------: | :-------------: |
| Frontier (Login Node)  | 25/1/1  | ✅   | ✅ | ✅   | ✅  |
| System Name  | Family/Model/Stepping | …

Add support for AMD family 25 (19h) processors in the RAPL component.

---

src/components/lmsensors/tests/Makefile
src/components/lmsensors/tests/lmsensors_list_events.c
src/components/lmsensors/tests/lmsensors_read.c

This PR addresses adding tests for the lmsensors component as currently none exist. 
This continues the updates for the overall GitHub CI for PAPI. As such, these tests will not take a command line argument; rather, we will search for events using `PAPI_enum_cmp_event`.
Truncated output for `lmsensors_list_events.c`:
```
Component index for lmsensors: 2
Event code Event name
1073741870 lmsensors:::coretemp-isa-0000.Package_id_0.temp1_input
1073741871 lmsensors:::coretemp-isa-0000.Package_id_0.temp1_max
1073741872 lmsensors:::coretemp-isa-0000.Package_id_0.temp1_crit
1073741873 lmsensors:::coretemp-isa-0000.Package_id_0.temp1_crit_alarm
....
Total number of events for lmsensor: 170
PASSED
```
Output for `lmsensors_read.c`:
```
Component index for lmsensors: 2
Successfully added …
```

Adding tests for the lmsensors component

---

src/configure
src/configure.in
src/darwin-common.c
src/darwin-common.h
src/darwin-memory.c
src/run_tests.sh
src/threads.c
src/utils/papi_multiplex_cost.c
src/utils/print_header.c

--disable-perf-event-uncore Disable perf_event_uncore component
--disable-perf-event    Disable perf_event component(disabling perf_event will disable perf_event_uncore as well)
--disable-cpu           Disable perf_event and perf_event_uncore component 
- Added `--disable-cpu`, `--disable-perf-event`, `--disable-perf-event-uncore`.
- Disabled `sysdetect` if perf-event is disabled
- Changed `AC_MSG_ERROR` → `AC_MSG_RESULT`.
- added `awk` statements to comment `ctest/ftest/vtest` in `Makefile.inc`.
- Reinstates them if disabling CPU is not specified.
- Changed a condition for enabling perf_events on for "if eval test \"x\$"$as_ac_File"\" = x"yes"; then :"
- Checks for `perf_event`.
- If not enabled, ctests ftests vtests do not run.
- Retrieve the current thread's ID using `pthread_self()`, …

Configure | run_test.sh : Disable perf_event and perf_event_uncore

---

src/components/intel_gpu/Rules.intel_gpu
src/components/intel_gpu/tests/Makefile
src/configure
src/configure.in

This pull request introduces changes to address Issue #283. 
These changes have been tested on the Intel Max 1550 GPU.

2024.12.11 intel gpu threads

---

.github/workflows/cat_workflow.yml

This PR fixes a small bug in the counter analysis toolkit CI where `cat tests` needs to be `cat_tests` in the `cat_workflow.yml`.

Fix for Bug in Counter Analysis Toolkit Workflow for PAPI CI

---

src/counter_analysis_toolkit/eventstock.c
src/counter_analysis_toolkit/main.c

With the features introduced in PR #237, CAT needs to be updated to operate in the absence of the perf_event component.
These changes have been tested on the NVIDIA Grace-Hopper architecture.

2024.11.12 cat bug

---

src/components/perf_event/perf_event.c

On systems with the kernel setting `perf_event_paranoid`>=2, userspace calls to `perf_event_open()` must set `attr.exclude_kernel=1`. Set `exclude_kernel=1` in `check_exclude_guest()` to allow the function to execute successfully on systems with `perf_event_paranoid`>=2;

perf_event: Eliminate paranoia error for check_exclude_guest()

---

src/run_tests.sh

This PR resolves Issue #302 by removing bash specific syntax. 
Tested on machines with Debian 12 and Rocky Linux 9.4.

Update run_tests.sh to remove bash specific syntax

---

src/libpfm4/include/perfmon/perf_event.h
src/libpfm4/lib/events/arm_neoverse_n1_events.h
src/libpfm4/lib/events/arm_neoverse_n2_events.h
src/libpfm4/lib/events/arm_neoverse_v1_events.h
src/libpfm4/lib/events/arm_neoverse_v2_events.h

Current with
commit d22403ec9bddaf62c59d847904918b30db69550d
Author: Stephane Eranian <eranian@gmail.com>
Date:   Fri Dec 13 00:42:42 2024 -0800
make L1I_CACHE_ACCESS an alias to the official L1I_CACHE event
Covers Neoverse N1, N2, N3, V1, V2.
L1I_CACHE_ACCESS is marked as deprecated.
Signed-off-by: Stephane Eranian <eranian@gmail.com>
commit 0003418f8b698cbb2709e7f6931c6fd94e634f98
Author: Stephane Eranian <eranian@gmail.com>
Date:   Fri Dec 13 00:23:03 2024 -0800
update perf_events interface header to 6.12
Update perf_event.h to reflect state in 6.12.
Signed-off-by: Stephane Eranian <eranian@gmail.com>
Testing was only done on an ARM Neoverse V2 as the PAPI team does not have access to an N1, N2, N3, or V1.
Testing:
- papi_avail successfully runs
- papi_component_avail successfully runs …

Update libpfm4 to commit 69550d

---

.github/workflows/papi_framework_workflow.yml

As of January 30th, 2025 `actions/upload-artifact@v3` has been deprecated and replaced with `actions/upload-artifact@v4`. See the following [article](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/) for more details.

Replace actions/upload-artifact@v3 with actions/upload-artifact@v4

---

src/configure
src/configure.in

When on Power 9 and Power 10 when running `./configure --prefix=$PWD/install-path`  you will run into the following errors:
```
grep: /include/cuda.h: No such file or directory
test: : integer expression expected
```
This PR updates `configure` and `configure.in` to avoid this.

Update configure and configure.in to avoid errors: integer expression expected and cuda.h no such file on Power 9 and 10

---

src/components/perf_event/perf_event.c

As stands, if a failure occurs in `check_exclude_guest` then one of the following errors will output: 
```
Couldn't open hw_instructions in exclude_guest=0 test.
or
Couldn't open hw_instructions in exclude_guest=1 test.
```
This PR updates both error messages to include:
```
Set /proc/sys/kernel/perf_event_paranoid to 2 (or less) or run as root.
```
Such that it indicates to users this is a `perf_event_paranoid` issue.
The PR needs to pass all the …

Updating error messages for function check_exclude_guest() in perf_event.c

---

src/components/rocp_sdk/README.md
src/components/rocp_sdk/rocp_sdk.c
src/components/rocp_sdk/sdk_class.cpp
src/components/rocp_sdk/sdk_class.hpp
src/components/rocp_sdk/tests/Makefile
src/components/rocp_sdk/tests/advanced.c
src/components/rocp_sdk/tests/kernel.cpp
src/components/rocp_sdk/tests/simple_sampling.c
src/components/rocp_sdk/tests/two_eventsets.c

The agent profiling mode (sampling) is now fully supported by the component. To activate it the user must set the environment variable RPSDK_MODE_AGENT_PROFILE=1.
However, the counter values returned by Rocprofiler-SDK when agent profiling is activated appear to be spurious.

ROCP_SDK: Enabling agent profiling mode.

---

src/components/cuda/cupti_dispatch.c
src/components/cuda/cupti_profiler.c
src/components/cuda/cupti_utils.h
src/components/cuda/linux-cuda.c
src/components/cuda/papi_cupti_common.c
src/components/cuda/papi_cupti_common.h

This PR adds support for heterogeneous gpu configurations. As a consequence the following were also updated:
- How we internally handle the default device id
- How we handle creating a context for users if one is not provided
Tested on Leconte (8 * V100) and Hexane (1 * V100 & 1 * H100):
| Test  | Pass |
| :-------------: | :-------------: |
| HelloWorld.cu  | :white_check_mark:   |
| HelloWorld_noCuCtx.cu  | :white_check_mark:  |
| concurrent_profiling.cu  | :white_check_mark:  |
| concurrent_profiling_noCuCtx.cu  | :white_check_mark:  |
| cudaOpenMP.cu | :white_check_mark:  |
| cudaOpenMP_noCuCtx.cu | :white_check_mark:  |
| pthreads.cu | :white_check_mark: |
| pthreads_noCuCtx.cu  | :white_check_mark: |
| simpleMultiGPU.cu  | :white_check_mark:  |
| simpleMultiGPU_noCuCtx.cu | …

Add Support for Heterogeneous GPU Configurations in the Cuda Component

---

src/components/rocm_smi/Rules.rocm_smi

In rocm 6.3, the location of rocm_smi has changed.  Setting `PAPI_ROCMSMI_ROOT=/opt/rocm/` is insufficient to point to the new location because the rocm_smi component "Rules" file appends "rocm_smi" to the include search path.  THis change to the Rules file will allow the component to find the header.

Adding location of rocm_smi header files for newer versions of rocm

---

src/components/rocp_sdk/tests/Makefile

Instead of explicitly setting the path for amdclang++ in the tests/Makefile, assuming that the compiler will be in the rocprofiler directory structure, allow it to be picked up from the environment PATH, or explicitly set through the new variable AMDCXX

ROCP_SDK: Change tests/Makefile for spack builds.

---

src/components/rocm_smi/README.md

Updated read me to note two cases of root path

rocm_smi: Update read me to note two cases of root path

---

src/components/perf_event_uncore/perf_event_uncore.c

Fixed issue #200 by reading capabilities using the `capget` system call. Now, users other than `root` can use PAPI to read uncore counters, provided they have one of the following capabilities: `CAP_SYS_ADMIN` or `CAP_PERFMON`.
- I opted to use the `capget` system call directly, not to add `libcap` as another dependency.
- I'd like to ask if there's any reason why system call numbers are manually defined. Would there
be any issue arising from the use of the `sys/syscall.h` header?
_Commits_ have a body (whenever relevant) containing a detailed description of the …

perf_event_uncore: consider capabilities for permissions

---

src/components/topdown/README.md
src/components/topdown/Rules.topdown
src/components/topdown/tests/Makefile
src/components/topdown/tests/topdown_L1.c
src/components/topdown/tests/topdown_L2.c
src/components/topdown/tests/topdown_basic.c
src/components/topdown/topdown.c
src/components/topdown/topdown.h

This PR adds a component that reads Intel's PERF_METRICS Model Specific Register (MSR) and extracts topdown micro-architecture analysis metrics from it, converting those metrics to percentages automatically for ease of use. For example:
$ ./utils/papi_command_line TOPDOWN_RETIRING_PERC TOPDOWN_BAD_SPEC_PERC \ 
TOPDOWN_FE_BOUND_PERC TOPDOWN_BE_BOUND_PERC
Successfully added: TOPDOWN_RETIRING_PERC
Successfully added: TOPDOWN_BAD_SPEC_PERC
Successfully added: TOPDOWN_FE_BOUND_PERC
Successfully added: TOPDOWN_BE_BOUND_PERC
TOPDOWN_RETIRING_PERC : 	20.784 %
TOPDOWN_BAD_SPEC_PERC : 	0.000 %
TOPDOWN_FE_BOUND_PERC : 	1.961 %
TOPDOWN_BE_BOUND_PERC : 	76.863 %
----------------------------------
Tested systems:
| **System Name** | **Family/Model/Stepping** | `papi_native_avail` | …

topdown: Created a component for interfacing with Intel's PERF_METRICS MSR

---

src/high-level/papi_hl.c
src/papi_vector.c

Recent PAPI compiles on Fedora rawhide (F42) fail because of "conflicting types" errors produced by GCC15.  Proper arguments types have been added to _internal_hl_read_user_events function declaration in papi_hl.c and the typecasting in papi_vector.c.
- [x ] **Description**
- [ x] **Commits**
- [x ] **Tests**

Eliminate conflicting type errors generated by GCC15

---

src/counter_analysis_toolkit/Makefile
src/counter_analysis_toolkit/cat_arch.h
src/counter_analysis_toolkit/vec.c
src/counter_analysis_toolkit/vec_fma_dp.c
src/counter_analysis_toolkit/vec_fma_hp.c
src/counter_analysis_toolkit/vec_fma_sp.c
src/counter_analysis_toolkit/vec_nonfma_dp.c
src/counter_analysis_toolkit/vec_nonfma_hp.c
src/counter_analysis_toolkit/vec_nonfma_sp.c
src/counter_analysis_toolkit/vec_scalar_verify.c
src/counter_analysis_toolkit/vec_scalar_verify.h

Include output for kernels that only execute scalar floating-point operations.
These changes have been tested on the Intel Sapphire Rapids and IBM POWER10 architectures.

cat: updates in vector-FLOPs benchmarks

---

src/components/perf_event_uncore/perf_event_uncore.c

Fix #338, where compiling `papi` fails due to the `CAP_PERFMON` macro not being defined.

Fix compilation when CAP_PERFMON is missing

---

src/components/cuda/cupti_profiler.c
src/components/rocm/roc_profiler.c

For both the Cuda component and the ROCm component, when adding events there is a an edge case where a user could successfully add events that had excess characters after the appended qualifier.  Example of this is shown below with the Cuda component:
```
./papi_command_line cuda:::dram__bytes.avg:device=0test
This utility lets you add events from the command line interface to see if they work.
Successfully added: cuda:::dram__bytes.avg:device=0test
cuda:::dram__bytes.avg:device=0test : 	268 
```
This PR addresses adding conditional checks to test for excess characters and properly return `PAPI_ENOEVNT` if applicable. The new behavior is outlined below:
```
[ICL:methane bin]$ ./papi_command_line cuda:::dram__bytes:stat=max:device=0dfdf
This utility lets you add events from the command …
```

Parse event qualifiers for the Rocm and Cuda components to make sure no excess characters are appended

---

src/components/rocm_smi/tests/Makefile

The rocm_smi component tests were not getting compiled during the build process. These updates point to the proper location of 'hipcc' and automatically builds the component tests. The 'square' test was removed due to the source file missing.
These changes have been tested with ROCm 6.3.1 on Frontier.

rocm_smi: updates to Makefile

---

src/components/rocm/roc_common.c
src/components/rocm/rocm.c

Previously, in the absence of a ROCm device, the rocm component did not set the string containing the reason that the component was disabled. This corresponds to Issue https://github.com/icl-utk-edu/papi/issues/220.
These changes have been tested with ROCm 6.3.1 on Frontier and ROCm 6.3.2 on a system with no ROCm devices.

rocm: add reason for disabled component

---

src/components/cuda/cupti_profiler.c
src/components/rocm/roc_profiler.c
src/components/rocm_smi/rocs.c
src/components/template/vendor_profiler_v1.c

PAPI_END is a macro defined in papiStdEventDefs.h to denote the end of the list of preset macros. However, it was being used as an error code in various components in cases unrelated to the number of presets.
This commit changes this to a more appropriate error code: PAPI_ENOEVNT.
These changes have been tested with ROCm 6.3.1 on Frontier and CUDA 12.1.1 on Methane.
This pull request addresses Issue #337.

components: improper usage of PAPI_END macro

---

src/components/rocp_sdk/Rules.rocp_sdk
src/components/rocp_sdk/rocp_sdk.c
src/components/rocp_sdk/tests/Makefile
src/components/rocp_sdk/tests/advanced.c
src/components/rocp_sdk/tests/kernel.cpp
src/components/rocp_sdk/tests/simple.c
src/components/rocp_sdk/tests/simple_sampling.c
src/components/rocp_sdk/tests/two_eventsets.c

This PR enables the rocp_sdk component to check the number of AMD GPUs on the system and gracefully fail if none are present. The tests also fail more gracefully in the absence of GPUs to run the kernels on.

ROCP_SDK: Accomodate machines with fewer AMD GPUs.

---

src/components/cuda/Rules.cuda
src/components/cuda/cupti_profiler.c
src/components/cuda/cupti_utils.h
src/components/cuda/lcuda_debug.h
src/components/cuda/linux-cuda.c
src/components/cuda/papi_cupti_common.c
src/components/cuda/papi_cupti_common.h
src/components/cuda/tests/concurrent_profiling.cu
src/components/cuda/tests/concurrent_profiling_noCuCtx.cu

This PR addresses Issue #225 by replacing the MetricsContext API with the MetricsEvaluator API. This makes it such that PAPI will now only support Cuda Toolkits 11.3 and greater. Note that with this change the overall event count will decrease as from NVIDIA certain sub-metrics are not useful for performance optimization.
Tested on Hexane (1 * H100 && 1 * V100) and Leconte (8 * V100s) with Cuda Toolkit 12.6:
- `papi_component_avail`, `papi_native_avail`, and `papi_command_line` - ✅
-  Cuda component tests - ✅ 
Tested on Heimdall ( 1 * RTX 5080) with Cuda Toolkit 12.8
- `papi_component_avail`, `papi_native_avail`, and `papi_command_line` - ✅
-  Cuda component tests - ✅  …

Cuda Component: Support the MetricsEvaluator API

---

src/components/perf_event/perf_event.c

This PR addresses Issue #354, where the `perf_event` component will show as active if your paranoid level is set to 4.
`./papi_component_avail`:
```
Available components and hardware information.
PAPI version             : 7.2.0.0
Operating system         : Linux 6.8.0-58-generic
Model string and code    : AMD Ryzen 9 9950X 16-Core Processor (68, 0x44)
CPU revision             : 0.000000
CPUID                    : Family/Model/Stepping 26/68/0, 0x1a/0x44/0x00
CPU Max MHz              : 5752
CPU Min MHz              : 600
Total cores              : 32
SMT threads per core     : 2
Cores per socket         : 16
Sockets                  : 1
Cores per NUMA region …
```

perf_event: Disable component if perf_event_paranoid is set to 4 

---

src/components/cuda/cupti_profiler.c
src/components/cuda/papi_cupti_common.c
src/components/cuda/papi_cupti_common.h
src/components/nvml/Rules.nvml
src/components/nvml/linux-nvml.c

This PR updates the closed PR #328 which requested to use numbered versions for the shared objects instead of unnumbered for runtime. Instead of hard coding the numbered versions, we now will dynamically search for the shared objects. 
For `libcuda`, `libcudart`, `libnvperf_host`, `libcupti`, and `libnvidia-ml`, there will be three naming schemes searched for:
- Unnumbered e.g. `libcudart.so`
- Numbered with .1 e.g. `libcudart.so.1`
- A catch all `libcudart` (for `libcudart` this would catch either `libcudart.so.12` or `libcudart.so.12.5.82`)
Testing was done on Methane at ICL (1 * A100) and Athena at Oregon (4 * A100s) using the PAPI utilities to verify:
- Setting `PAPI_CUDA_ROOT` to Cuda Toolkit install directory: ✅ 
- Setting Cuda and NVML environment variables (`PAPI_CUDA_RUNTIME`, …

Cuda/NVML Components: Dynamically Search for the Shared Objects

---

src/components/cuda/cupti_config.h
src/components/cuda/cupti_dispatch.c
src/components/cuda/cupti_dispatch.h
src/components/cuda/cupti_events.c
src/components/cuda/cupti_profiler.c
src/components/cuda/linux-cuda.c
src/components/cuda/papi_cupti_common.c
src/components/cuda/papi_cupti_common.h
src/papi.h
src/papi_internal.c
src/utils/papi_component_avail.c

This PR will address half of the topic **Systems with multiple GPU configurations**  in Issue #297.  This is done by creating a partially disabled `Cuda` component to monitor NVIDIA devices with compute capabilities greater than or equal to 7.0 on machines with mixed compute capabilities (e.g. 6.0 - P100, 7.0 - V100, and 8.0 - A100). 
Cuda component output from `papi_component_avail` on a machine with an A100, V100, and P100:
```
Compiled-in components:
Name:   cuda                    CUDA profiling via NVIDIA CuPTI interfaces
\-> Partially disabled: System includes multiple compute capabilities: <7.0, =7.0, >7.0. Only support for CC >=7.0 enabled. As a result, Device IDs: 0,1 are available.
Active components:
Name:   cuda                    CUDA profiling via NVIDIA CuPTI interfaces …
```

Cuda Component: Support Partially Disabled Cuda Component with CCs >= 7.0 (Perfworks API)

---

src/components/rocp_sdk/rocp_sdk.c
src/components/rocp_sdk/sdk_class.cpp

When applications are linked against libpapi.a rocprofiler_configure() is not called on-load, so we have to explicitly initialize everything. This PR moves some of the necessary steps earlier, so that everything is initialized after PAPI_library_init().

ROCP_SDK: call configure_device_counting_service as early as possible.

---

src/components/cuda/cupti_profiler.c

This PR replaces the `int` datatype of `metricValues` in `cuptip_ctx_read` with `long long` such that we avoid overflow with measured values.
As stands with the current master branch if you run the `concurrent_profiling` test with cuda:::sm__cycles_active:stat=sum:device=0 you will end up with a negative value: 
```
Metrics for device #0:
Look at the sm__cycles_elapsed.max values for each test.
This value represents the time spent on device to run the kernels in each case, and should be longest for the serial range, and roughly equal for the single and multi device concurrent ranges.
PAPI event name							Measured value
cuda:::sm__cycles_active:stat=sum:device=0			-2147483648
PASSED
```
This PR resolves this …

Cuda component: Replace int typing with long long to avoid overflow with measured values

---

src/components/coretemp/linux-coretemp.c

As stands, the Coretemp component does not support multiplexing. Due to this, if you try to add a Coretemp event to a multiplexed EventSet you will be met with `PAPI_EINVAL`.
This PR updates the Coretemp component to allow for multiplexing. 
Tested with the below application code using `PAPI_assign_eventset_component` and `PAPI_add_event` on an Intel Xeon Gold 6140 (Methane at ICL as of May 7th, 2025):
```c
#include <papi.h>
#include <stdio.h>
#include <stdlib.h>
void handle_error (int retval)
{
printf("PAPI error %d: %s\n", retval, PAPI_strerror(retval));
exit(1);
}
int main()
{
int retval = PAPI_library_init(PAPI_VER_CURRENT);
if (retval != PAPI_VER_CURRENT) {
handle_error(retval);
}   
retval = PAPI_multiplex_init();
if (retval != PAPI_OK) {
handle_error(retval);
}   
int EventSet = …
```

Coretemp: Enable support for multiplexing

---

src/components/cuda/cupti_profiler.c
src/components/rocm/roc_profiler.c

As stands the Cuda and ROCm components will allow the following cases of events to be added:
Cuda:
```
cuda:::dram__bytes:stat=max:device=0:stat=max:device=0
cuda:::dram__bytes:stat=max:device=0:stat=max:device-0
cuda:::dram__bytes:stat=max:device=0:stat=max:device=-0
```
ROCm:
```
rocm:::TCC_EA1_WRREQ_64B:device=0:instance=1:device=0:instance=0
rocm:::TCC_EA1_WRREQ_64B:device=-0:instance=1
```
None of the above cases are valid events. This PR addresses this and adds stricter checks for qualifiers and will now fail on the above instances. Verification for the new behavior was done with `papi_command_line` for the following setups:
- Cuda component: 8 * A100s with Cuda Toolkit 12.8
- ROCm component: 2 * Vega 20s with ROCm 6.3.2
_Why_ this PR exists. Reference all relevant information, …

Cuda/ROCm components: Add stricter qualifiers checks

---

src/linux-context.h
src/linux-timer.c
src/mb.h

Add loongarch64 support.
Compiling the papi failed for loong64 in the Debian Package Auto-Building environment.
The full compilation log can be found at 
https://buildd.debian.org/status/logs.php?pkg=papi&ver=7.0.1-1&arch=loong64
```
./linux-context.h:43:2: error: #error "OVERFLOW_ADDRESS() undefined!"
43 | #error "OVERFLOW_ADDRESS() undefined!"
|  ^~~~~
In file included from ./linux-lock.h:4,
from ./papi_lock.h:20,
from ./papi_internal.h:437:
./mb.h:67:2: error: #error Need to define rmb for this architecture!
67 | #error Need to define rmb for this architecture!
```
Now, papi was built successfully on loongarch64.
Details can be found at https://buildd.debian.org/status/logs.php?pkg=papi&ver=7.1.0-5%2Bb1&arch=loong64.
Please review.

Add loongarch64 support

---

src/components/cuda/cupti_dispatch.c

Currently there is a case where `cuptid_init` will not properly return a PAPI error code if you enter the following conditional block:
```
int init_errno = cuptic_init();
if (init_errno != PAPI_OK && init_errno != PAPI_PARTIAL) {
goto fn_exit;
}   
```
As when you hit the `goto fn_exit` we jump to `fn_exit` and return `papi_errno`. Which at this point has not been set. This can end up resulting in a segfault if the Cuda shared objects are not found (tested on 1 * GH200):
```
[tburgess@hopper1 bin]$ unset PAPI_CUDA_ROOT
[tburgess@hopper1 bin]$ module unload cuda/12.6.3
[tburgess@hopper1 bin]$ ./papi_component_avail
Segmentation fault (core dumped)
```
This PR updates the conditional block to now be:
```
int papi_errno;
int init_errno = cuptic_init();
if (init_errno != PAPI_OK && init_errno …
```

Cuda component: Properly set return value in cuptid_init

---

src/configure
src/configure.in

As stands, if a user configures with the following: `./configure --prefix=$PWD/test-install --with-tests="comp_tests"` then the output for "checking for tests" will be incorrect:
```
checking for tests... checking for debug build... 
```
This will also occur for other options of `--with-tests` such as "comp_tests ftests" or "comp_tests ftests ctests".
Along with the above issue with `--with-tests`, if `--with-debug` is not set then configure will output:
```
checking for debug build...
```
This PR resolves both of these bugs/behaviors:
```
--with-tests:
./configure --prefix=$PWD/test-install --with-tests="comp_tests"
checking for tests... comp_tests
./configure --prefix=$PWD/test-install --with-tests="comp_tests ftests ctests"
checking for tests... ctests ftests comp_tests
Without …
```

Configure: Correctly output the tests chosen by a user with `--with-tests` and default value for `--with-debug`

---

src/components/rocm/roc_profiler.c

This PR fixes a typo in `rocm_verify_no_repeated_qualifiers`. In ROCm we should be checking for a `device` and `instance` qualifier. PR #362 introduced a typo that saw us checking for a `stat` qualifier instead of an `instance` qualifier. 
This PR resolves the typo and now correctly errors if more than two instance qualifiers are provided:
```
[ICL:histamine2 bin]$ ./papi_command_line rocm:::TCC_EA1_WRREQ:instance=0:device=0:instance=0
This utility lets you add events from the command line interface to see if they work.
Failed adding: rocm:::TCC_EA1_WRREQ:instance=0:device=0:instance=0
because: Event does not exist
No events specified!
Try running something like: ./papi_command_line PAPI_TOT_CYC
```
Tested this fix on a Vega 20 with ROCm 6.3.2.
_Why_ this PR exists. Reference all relevant …

ROCm component: Bug fix for typo in rocm_verify_no_repeated_qualifiers

---

src/components/appio/appio.c

Currently if you run `./papi_component_avail` the `appio` component will not have a description shown:
```
Compiled-in components:
Name:   appio                   
Active components:
Name:   appio                   
Native: 45, Preset: 0, Counters: 45
```
This PR addresses this by adding a description in the component vector of `appio`, now `./papi_component_avail` shows:
```
Compiled-in components:
Name:   appio                   Linux I/O system calls
Active components:
Name:   appio                   Linux I/O system calls
Native: 45, Preset: 0, Counters: 45
```
Tested this change on a machine with an Intel Xeon Gold 6140. …

Appio Component: Add a component description, as it is missing from `papi_component_avail`

---

src/components/cuda/tests/HelloWorld.cu
src/components/cuda/tests/HelloWorld_noCuCtx.cu
src/components/cuda/tests/concurrent_profiling.cu
src/components/cuda/tests/concurrent_profiling_noCuCtx.cu
src/components/cuda/tests/cudaOpenMP.cu
src/components/cuda/tests/cudaOpenMP_noCuCtx.cu
src/components/cuda/tests/pthreads.cu
src/components/cuda/tests/pthreads_noCuCtx.cu
src/components/cuda/tests/runtest.sh
src/components/cuda/tests/simpleMultiGPU.cu
src/components/cuda/tests/simpleMultiGPU_noCuCtx.cu
src/components/cuda/tests/test_2thr_1gpu_not_allowed.cu
src/components/cuda/tests/test_multi_read_and_reset.cu

This PR updates the Cuda component tests to more gracefully handle multiple pass events if they are added on the command line. The current master branch behavior will see a test fail or skipped if a multiple pass event is provided. 
For the tests listed below:
- `HelloWorld.cu`, `HelloWorld_noCuCtx.cu`, `simpleMultiGPU.cu`, `simpleMultiGPU_noCuCtx.cu`, `concurrent_profiling.cu`, `concurrent_profiling_noCuCtx.cu`, `pthreads.cu`, `pthreads_noCuCtx.cu`, `cudaOpenMP.cu`, `cudaOpenMP_noCuCtx.cu`, and `test_multi_read_and_reset.cu`
the updated behavior will see two scenarios, 
1. If you provide only multiple pass events we output the following message:
```
Events provided on the command line could not be added to an EventSet as they require multiple passes.
```
2. If you provide a multiple pass …

Cuda component: Update tests to more gracefully handle multiple pass events

---

src/components/README

PR #191 removed the `perfctr` and `perfctr_ppc` components. This PR removes leftover documentation in the `components` README.

Remove perfctr documentation and leftover code from PR #191

---

src/utils/print_header.c

On a machine with a Power 9 using GCC version 4.8.5 if you run `make` after you `configure` (e.g. `./configure --prefix=$PWD/test-install`) the following error occurs:
```
print_header.c: In function ‘papi_print_header’:
print_header.c:79:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
for (int cid = 0; cid < numcmp; cid++ ) {
^
print_header.c:79:2: note: use option -std=c99 or -std=gnu99 to compile your code
```
This PR resolves this by moving the for loop counter declaration outside of the for loop header in `print_header.c`.
Tested on a Power 9 with GCC version 4.8.5 and built successfully with the utilities: `papi_component_avail`, `papi_native_avail`, and `papi_command_line` running as expected.
As a sanity check, I also tested on an AMD EPYC 7413 with GCC …

utils/print_header.c: Move for loop counter declaration out of for loop header.

---

src/papi_preset.c

This makes the usage of memory allocation and freeing functions consistent to prevent segmentation faults when using preset events, as documented in Issue #383.
These changes were tested on the ARM Neoverse-V2 and NVIDIA Hopper architectures.

framework: proper memory management functions

---

src/components/cuda/linux-cuda.c

This PR initializes the `count` variable in the function`cuda_init_private` to be 0. Without `count` being initialized junk values will show when you run `./papi_component_avail` when configured with `--with-debug=memory`:
Note: My configure is as follows for tests shown below: `./configure --prefix=$PWD/test-install --with-sysdetect=no --with-components="cuda" --with-debug=memory`
```
Compiled-in components:
Name:   cuda                    CUDA profiling via NVIDIA CuPTI interfaces
Active components:
Name:   cuda                    CUDA profiling via NVIDIA CuPTI interfaces
Native: 94561, Preset: 6, Counters: 30
```
Setting `count=0`, will show the correct count (Tested on an H100 with Cuda Toolkit 12.6.3):
```
Compiled-in components:
Name:   cuda                    CUDA profiling via …
```

Cuda component: Initialize count variable in function cuda_init_private

---

src/components/lmsensors/linux-lmsensors.c

Currently in the `lmsensors` component there are two `fprintf` calls. This can lead to error messages printing even when you do not set `PAPI_DEBUG`. As an example, on an AMD Epyc 7413 with `lmsensors` 3.4 the following will occur:
```
[tburgess@gilgamesh bin]$ ./papi_command_line lmsensors:::amdgpu-pci-e300.mem.temp3_crit
This utility lets you add events from the command line interface to see if they work.
libsensors(): Could not read event #26!
.
.
.
libsensors(): Could not read event #75!
Successfully added: lmsensors:::amdgpu-pci-e300.mem.temp3_crit
lmsensors:::amdgpu-pci-e300.mem.temp3_crit : 	94000 
```
This PR resolves this issue by replacing the `fprintf`'s with `SUBDBG`'s (Tested on an AMD Epyc 7413 with `lmsensors` 3.4).
_Why_ this PR exists. Reference all relevant information, …

lmsensors component: Replace fprintf with SUBDBG

---

src/components/infiniband/linux-infiniband.c
src/components/nvml/linux-nvml.c
src/components/sysdetect/sysdetect.c
src/components/topdown/topdown.c
src/components/topdown/topdown.h

This PR resolves Issue #366. 
The following components saw updates to `.size` in their component vectors:
| Component  | Update done | Status of `papi_component_avail` and `papi_native_avail` after updates |
| ------------- | ------------- | ------------- |
| `sysdetect`  | Added `.size` with default values |   * `papi_component_avail` - ✅  <br> * `papi_native_avail` - ✅   |
| `topdown`  | Added a junk int to `_topdown_context_t` | * `papi_component_avail` - ✅  <br> * `papi_native_avail` - ✅  |
| `infiniband`  | Set `.reg_alloc` to have a value of 1  | * `papi_component_avail` - ✅  <br> * `papi_native_avail` - ✅  |
| `nvml`  | Set `.reg_alloc` to have a value of 1  | * `papi_component_avail` - ✅  <br> * `papi_native_avail` - ✅ |
The following components were tested and did not have `Error …

Sysdetect/Topdown/Infiniband/NVML Components: Resolves Cases Where `Error! PAPI_library_init` Occurs with `--with-debug=memory`

---

src/components/rocm_smi/linux-rocm-smi.c
src/components/rocp_sdk/rocp_sdk.c
src/components/template/template.c

As stands both `rocm_smi` and `rocp_sdk` have the following `fn_exit`/`fn_fail` structure:
```
fn_exit:
_component_vector.cmp_info.initialized = 1;
fn_fail:
goto fn_exit;
```
Therefore, if either component fails to initialize at any point in their respective `init_private` functions we would goto `fn_fail` and then `fn_exit` which would result in `initialized` being set to 1 which would not be true. 
This PR resolves this behavior and correctly will have `initialized` set to 0 if either fail at any point inside their respective `init_private` functions.
Testing was done on Intel Xeon Gold 6140 with an NVIDIA A100 (no AMD Devices on the machine).  As a note, I tested on a machine without AMD devices to trigger a failure at the `init_private` functions.
_Why_ this PR exists. Reference all …

rocm_smi/rocp_sdk: Restructure init_private functions to avoid setting initialized equal to 1 even when initialization fails

---

src/components/coretemp/linux-coretemp.c
src/components/cuda/cupti_profiler.c
src/components/cuda/cupti_utils.c
src/components/cuda/htable.h
src/components/cuda/linux-cuda.c
src/components/cuda/papi_cupti_common.c
src/components/infiniband/linux-infiniband.c
src/components/net/linux-net.c
src/components/rocm/htable.h
src/components/rocm_smi/htable.h
src/components/rocm_smi/rocs.c

This PR addresses components mixing C memory allocation and PAPI memory allocation. This becomes an issue when you add the flag `--with-debug=memory` as:
1. PAPI memory allocation creates extra metadata
2. Trying to `papi_free` a variable that was allocated with just `malloc`, `calloc`, or `realloc` will result in a segmentation fault
Below are Components that have changes done to them:
|Component | Memory Allocation Used Before Changes | Memory Allocation Used After Changes | Tests Ran | Hardware Tested On | Kernel Versioning |
| ------------- | -------------| ------------- | ------------- | ------------- | ------------- |
|  `rocm_smi` | Mixed  | PAPI | *`papi_component_avail` - ✅ <br> *`papi_native_avail` - ✅ <br> *`papi_command_line` - ✅  <br> *Application Code with `PAPI_shutdown` - …

Various Components: Avoid Mixed Memory Allocation

---

src/components/rocp_sdk/rocp_sdk.c

This PR removes the assignments of `info->event_code` and `info->component_index` in `rocp_sdk` specifically in the function titled `rocp_sdk_ntv_code_to_info` in the source file `rocp_sdk.c`.
This is being done as in `papi_internal.c` the function titled `_papi_hwi_get_native_event_info` already assigns both of the variables a value. 
Specifically for the case of `info->event_code` this would lead to an incorrect `event_code` assignment which can be seen from `PAPI_get_event_info` output:
```
Event Code: 0 // incorrect
Symbol: rocp_sdk:::cache_lines_per_tag
Short Descr: Constant value cache_lines_per_tag from agent properties
Long Descr: Constant value cache_lines_per_tag from agent properties
Component Index: 2
```
This PR resolves the above issue with `info->event_code`:
```
Event …
```

rocp_sdk: Remove assignment of info->event_code and info->component_index in rocp_sdk as it is already done in papi_internal.c

---

src/papi.c

This PR updates the documentation for `PAPI_list_events` in `papi.c` as follows:
```
from:
int PAPI_list_events(int *EventSet, int *Events, int *number );
to:
int PAPI_list_events(int EventSet, int *Events, int *number);
```
This is such that we match the actual function prototype.
I have verified that this updated documentation shows when running `doxygen Doxyfile-html` and `doxygen Doxyfile-man3`, see below.
man3 documentation for `PAPI_list_events`:
```
#include <\fBpapi\&.h\fP> 
.br
int PAPI_list_events(int EventSet, int *Events, int *number);
.RE
```
Generated html page:
```
C Interface
#include <papi.h>
int PAPI_list_events(int EventSet, int *Events, int *number);
``` …

PAPI_list_events: Update functions documentation to match the function prototype

---

src/components/rocm/README.md

This PR updates the `rocm` component `README.md` with two new limitations which can be seen below:
1. The `rocm` component is deprecated starting at the AMD Instinct MI300A and will continue to be for any future AMD device releases. Please instead use the [`rocp_sdk`](https://github.com/icl-utk-edu/papi/blob/master/src/components/rocp_sdk/README.md) component.
2. For AMD devices older than the AMD Instinct MI300A, PAPI should not be configured with both `rocm` and `rocp_sdk`.
_Commits_ have a body (whenever relevant) containing a detailed description of the …

rocm: Update the component README.md to account for new limitations.

---

src/components/intel_gpu/Rules.intel_gpu

In the file `Rules.intel_gpu`, `DEBUG` will be defined as a macro with definition 1. This macro is normally only defined when a user adds `--with-debug={yes, memory}` when configuring PAPI.  Defining the macro `DEBUG` in `Rules.intel_gpu` will cause a users build to act as if they did provide `--with-debug={yes, memory}` when configuring.
For example, in `PAPI_num_events`, the following block of code wrapped in an `ifdef` and `endif` will be triggered when configured with the `intel_gpu` component:
```
int
PAPI_num_events( int EventSet )
{
APIDBG( "Entry: EventSet: %d\n", EventSet);
EventSetInfo_t *ESI;
ESI = _papi_hwi_lookup_EventSet( EventSet );
if ( !ESI )
papi_return( PAPI_ENOEVST );
#ifdef DEBUG
/* Not necessary */
if ( ESI->NumberOfEvents == 0 )
papi_return( PAPI_EINVAL );
#endif …
```

intel_gpu: Remove -DDEBUG from Rules.intel_gpu

---

src/components/cuda/linux-cuda.c
src/papi.c
src/papi_internal.c
src/papi_preset.c
src/papi_vector.c
src/papi_vector.h

PR #284 introduced code that always forced the initialization of all components. However, this defeats the purpose of having PAPI_EDELAY_INIT.
The changes in this pull request only force initialization of components when necessary.
These changes have been tested on systems containing:
- NVIDIA Hopper architecture
- AMD Zen3 CPU and AMD MI250X GPU architectures (Frontier).
This pull request addresses Issue #385.

framework: force init per existing policy

---

src/components/rapl/linux-rapl.c

This PR adds RAPL support for Intel Emerald Rapids CPUs.  For the RAPL case, I verified the model number (207) via a [post](https://www.redhat.com/en/blog/red-hat-enterprise-linux-performance-results-5th-gen-intel-xeon-scalable-processors) by Red Hat that shows the hardware configuration.
**Note at this time the PAPI team does not have access to a machine with an Intel Emerald Rapids CPU to verify this addition**.
As a sanity check, I configured and built PAPI as follows `./configure --prefix=$PWD/test-install --with-components="rapl"` on an Intel Xeon Gold 6430 (Sapphire Rapids - Family/Model/Stepping 6/143/8). The build was successful, with the utilities `papi_avail`, `papi_component_avail`, `papi_native_avail`, and `papi_command_line` working as expected (`rapl` was disabled as I …

RAPL Component: Add support in RAPL for Intel Emerald Rapids

---

src/components/cuda/linux-cuda.c
src/components/rocm/rocm.c
src/components/template/template.c

This PR updates the function `update_native_events` in the `rocm` and `cuda` components such that `realloc` is not called on a size of 0. As when `realloc` is called on a size of 0 the behavior is implementation defined.
This edge case can occur in the following workflow: 
```
#include "papi.h"
#include <stdio.h>
#include <stdlib.h>
int main() {
int retval = PAPI_library_init(PAPI_VER_CURRENT);
if (retval != PAPI_VER_CURRENT) {
printf("Call to PAPI_library_init: %d\n", PAPI_ENOINIT);
exit(1);
}   
retval = PAPI_get_component_index("rocm");
if (retval < PAPI_OK) {
printf("Call to PAPI_get_component_index failed: %d\n", retval);
exit(1);
}   
int cmpIdx = 2;
int i = 0 | PAPI_NATIVE_MASK;
retval = PAPI_enum_cmp_event( &i, PAPI_ENUM_FIRST, cmpIdx);
if (retval != PAPI_OK) {
printf("Call to …
```

cuda/rocm components: Restructure update_native_events to not call realloc on a size of 0

---

src/components/rocm/tests/Makefile
src/components/rocm_smi/tests/Makefile

This PR addresses the following two items:
1. For both `rocm` and `rocm_smi` this PR allows users to optionally set `HIPCC` for `tests/Makefile` if it is not found in the path designed by the environment variable `PAPI_ROCM_ROOT`.
2. For `rocm_smi`, the test `rocmsmi_example.cpp` becomes an optional test. This is being done as the test requires `rocblas` which is one of the longest to build packages in spack. For more information, please see Geri's comment [here](https://github.com/icl-utk-edu/papi/pull/388#issuecomment-2917126368).
I tested both of these changes on Gilgamesh at Oregon (2 * Instinct MI210s) with ROCm 6.1.3, results are below:
- For item **1.**, I was able to optionally set `HIPCC` for both `rocm/tests/Makefile` and `rocm_smi/tests/Makefile`.
- For item **2.**, …

rocm/rocm_smi: Allow users to optionally set HIPCC

---

src/components/rocm/tests/multi_thread_monitoring.cpp

On Frontier, the invocation of the `exit()` call before `pthread_merge()` causes a segmentation fault. I remedy this issue by only calling `test_warn()`, `test_fail()`, and `hip_test_fail()` after the threads have been merged.
These changes were tested using ROCm versions 6.1.3, 6.2.0, 6.2.4, 6.3.1, and 6.4.0 with the AMD MI250X architecture on the Frontier supercomputer.
This pull request addresses Issue #421.

rocm: fix segmentation fault in component test

---

src/utils/papi_avail.c

Currently in the master branch if PAPI is configured as follows: `./configure --prefix=$PWD/test-install`. `papi_avail` will have the following output:
```
.
.
.
PAPI_VEC_SP  0x80000069  Yes   Yes  Single precision vector/SIMD instructions
PAPI_VEC_DP  0x8000006a  Yes   Yes  Double precision vector/SIMD instructions
PAPI_REF_CYC 0x8000006b  Yes   No   Reference clock cycles
Of 108 possible events, 59 are available, of which 18 are derived.
```
This PR updates `papi_avail.c` to print the final format line even in the case that PAPI is only configured with the default components.
Testing was done on a machine with an Intel Xeon Gold 6140 with 1 * A100 using Cuda Toolkit 12.6.
`./papi_avail` with `./configure --prefix=$PWD/test-install`:
```
.
.
.
PAPI_VEC_SP  0x80000069  Yes   Yes  Single …
```

papi_avail.c: Move print statement for final format line to output even if only the default components are configured

---

src/components/rocm_smi/tests/Makefile

Currently in the master branch if you configure PAPI as follows: `./configure --prefix=$PWD/test-install --with-components="sde rocm_smi"` you will run into the below linker error:
```
ld.lld: error: undefined symbol: timer_create
>>> referenced by sde.c:729 (components/sde/sde.c:729)
>>>               sde.o:(do_set_timer_for_overflow) in archive ../../../libpapi.a
ld.lld: error: undefined symbol: timer_delete
>>> referenced by sde.c:688 (components/sde/sde.c:688)
>>>               sde.o:(_sde_set_overflow) in archive ../../../libpapi.a
>>> referenced by sde.c:846 (components/sde/sde.c:846)
>>>               sde.o:(_sde_dispatch_timer) in archive ../../../libpapi.a
>>> referenced by sde.c:288 (components/sde/sde.c:288)
>>>               sde.o:(_sde_stop) in archive ../../../libpapi.a
>>> …
```

rocm_smi: Update tests/Makefile to properly link with existing LDFLAGS e.g. -lrt

---

src/configure.in

This PR removes the flag `--with-libpfm4` mentioned in the cross compile sample comment in `configure.in` as this flag does not exist anymore.
If you run `./configure --prefix=$PWD/test-install --with-libpfm4`, you will get back a warning:
```
configure: WARNING: unrecognized options: --with-libpfm4
```
Tested on an Intel Xeon Gold 6140 with the following configure: `./configure --prefix=$PWD/test-install`. The utilities: `papi_avail`, `papi_component_avail`, `papi_native_avail`, and `papi_command_line` all work as expected.
_Commits_ have a body (whenever …

configure.in: Remove flag --with-libpfm4 from cross compile sample comment

---

src/components/net/tests/net_values_by_name.c

Currently in the master branch if you try to run the `net` component test `net_values_by_name.c` it will not successfully run:
```
Net events by name
FAILED!!!
Line # 60 Error in PAPI_event_name_to_code: Not supported by component
Some tests require special hardware, permissions, OS, compilers
or library versions. PAPI may still function perfectly on your 
system without the particular feature being tested here.  
```
This PR updates the `net_values_by_name.c` by:
- Not hard coding the net native event names and instead enumerating through the available net events.
- Actually using `PAPI_add_named_event` instead of `PAPI_add_events`. As the test name indicates we will get the net values by name.
Testing of this PR was done on an Intel Xeon Gold 6430 with RHEL 8.10. Snippet of output for …

net: Update the test net_values_by_name.c to successfully run and not use hard coded events

---

src/maint/genpapifdef.pl

Changes how perl in found on the system for the genpapifdef.pl script (shebang) to allow for other locations than `/usr/bin/perl`.
After #5, installing papi requires perl to be installed at `/usr/bin/perl`. However, this is not always the case.
In particular, I was running into "no such file or directory" while trying to install papi in Spack CI context (in a centos 7 container). See https://github.com/spack/spack-packages/pull/869
The minimal fix consisted in 2 things: 
- Add perl as a build dependency for papi. (necessary but not sufficient).
- Change the script shebang to allow for another location.
_Commits_ have a body (whenever relevant) containing a detailed …

Get perl from env instead of hard-coded path

---

src/components/cuda/linux-cuda.c

In PAPI master the `cuda_stop` `SUBDBG` message `"Error! Cannot PAPI_stop counters for an eventset that has not been PAPI_start'ed."` lacks a newline and results in the following output when `PAPI_DEBUG` is exported to be equal to `SUBSTRATE`
```
SUBSTRATE:components/cuda/linux-cuda.c:cuda_stop:614:262800 Error! Cannot PAPI_stop counters for an eventset that has not been PAPI_start'ed.SUBSTRATE:components/cuda/linux-cuda.c:cuda_stop:635:262800 EXIT: Unknown error code
```
This PR adds a newline to the end of this `SUBDBG` message.
Testing was done on Voltar at Oregon, the machine details are as follows:
```
CPU: Intel Xeon Gold 6226R
GPUs: 1 * P100, 1 * V100, 1 * A100
OS: RHEL 8.10
CUDA Toolkit: 12.6.3
```
Now when exporting `PAPI_DEBUG` to be equal to `SUBSTRATE` the output shows as:
``` …
```

cuda: Add newline for SUBDBG message in cuda_stop

---

src/components/rocm_smi/Rules.rocm_smi
src/components/rocm_smi/rocs.c

Currently, PAPI does not expose the `rsmi_dev_energy_count_get` and `rsmi_dev_current_socket_power_get` functions.
These functions are exceedingly important for HPC researchers to measure the energy costs of different workloads across AMD machines.
This PR works in conjunction with the [2 line PR to ROCm/rocm_smi_lib which adds these counters to the device function map](https://github.com/ROCm/rocm_smi_lib/pull/222).
The PR needs to pass all the …

rocm_smi: Expose energy and power consumption measurements

---

src/components/rocp_sdk/tests/Makefile
src/components/rocp_sdk/tests/advanced.c
src/components/rocp_sdk/tests/helper_rocp_sdk.c
src/components/rocp_sdk/tests/simple.c
src/components/rocp_sdk/tests/simple_sampling.c
src/components/rocp_sdk/tests/two_eventsets.c

This PR updates the `rocp_sdk` component tests to be able to enumerate through the available native events on a device if none of the desired events in the application test code exist.
This PR was tested on two difference machines.
- First machine: 2 * MI50 using ROCm 6.4.0 
- `advanced.c`: ✅ 
- `simple.c`: ✅ 
- `simple_sampling.c`: ✅ 
- `two_eventsets.c`: ✅ 
Note: For this machine, the tests would run with random events.
- Second machine: 2 * MI210 using ROCm 6.4.0
- `advanced.c`: ✅ 
- `simple.c`: ✅ 
- `simple_sampling.c`: ✅ 
- `two_eventsets.c`: ✅ 
Note: For this machine, the tests would run with the desired events. Along with testing the desired events ran, I modified the helper functions to only collect two desired events. In this case the tests would only run with the two desired …

rocp_sdk: Update component tests to enumerate through available events and add them if none of the desired events can be added

---

.github/ISSUE_TEMPLATE/papi_feature_request.yml
.github/ISSUE_TEMPLATE/papi_issue_report.yml
.github/workflows/ci_default_components.sh
.github/workflows/ci_individual_component.sh
.github/workflows/ci_papi_framework.sh
.github/workflows/papi_framework_workflow.yml
.github/workflows/rocp_sdk_component_workflow.yml
src/run_tests.sh

This PR updates the PAPI GitHub CI:
1. Two new issue templates are being added.
- The first template is specifically for PAPI bug related issues and will request more information from a user early on in regards to their machine (e.g. cpu, gpu, etc.).
- The second template is a feature request template.
Note that the blank issue will still persist with this change.
2. `rocp_sdk` jobs are now added.
3.  Increased robustness for checking expected active components.
- Currently when checking expected active components the order of the components matters. With this PR this is no longer the case. 
_Commits_ have a header of the form: …

PAPI CI: Add `rocp_sdk` jobs, improve robustness of checking for expected active components, and add issue templates

---

src/components/sysdetect/tests/Makefile

This PR resolves Issue #473.
I chose to use a shell approach compared to using `findstring` as the former is case insensitive while the latter is case sensitive. 
Testing was done on two machines.
First, llyad at Oregon with the following machine info:
- CPU: AMD EPYC 7402
- OS: RHEL 8.10 
| Name of Executable  | PAPI Build | Sysdetect Component Tests Build and Run |
| ------------- | ------------- | ------------- |
| `gfortran`  | ✅  | ✅  |
| `/home/users/tburgess/gfortran_executable/13.2.0/bin/gfortran-13`  | ✅  | ✅  |
| `/home/users/tburgess/gfortran_executable/13.2.0/bin/gfortran13`  | ✅  | ✅  |
|`/home/users/tburgess/gfortran_executable/13.2.0/bin/Gfortran13` | ✅  | ✅  |
|`/home/users/tburgess/gfortran_executable/13.2.0/bin/GFORTRAN13` | ✅  | ✅ |
Second, Pinwheel at Oregon with the …

sysdetect: Allow for gfortran executable variants

---

src/components/perf_event/perf_event.c
src/configure
src/configure.in

This PR adds:
- Updated message for `configure` if the `perf_event_paranoid` level is above 2
- Updated message for `perf_event` when using `papi_component_avail` if the component is disabled due to the `perf_event_paranoid` level being insufficient
- The ability to use `CAP_SYS_ADMIN` or `CAP_PERFMON` with the `perf_event` component
Testing was done in a docker container on a machine with:
- CPU: Intel Xeon Gold 6140
- OS: Rocky Linux 9.5
1. If the `perf_event_paranoid` level was insufficient then in both cases `configure` and `papi_component_avail` would output the updated messages.
`configure`:
```
***************************************************************************
* Insufficient permissions for accessing any hardware counters.           *
* Your current paranoid level is 3. …
```

perf_event: Allow for the use of CAP_SYS_ADMIN and CAP_PERFMON

---

.github/workflows/ci_individual_component.sh
.github/workflows/ci_papi_framework.sh

Some of the ICL systems, namely Guyot and Hexane have been updated to support Cuda Toolkit 13. Due to this change, these systems see their system-installed Cuda Toolkit versions' be 13. Therefore, we must tell the system at runtime where to find the library; otherwise, we run into the error `error while loading shared libraries: libcudart.so.12`.
This PR updates the Cuda component tests to now:
- Explicitly set the path to `libcudart.so` using `LD_LIBRARY_PATH`.
- Explicitly set the path to `libcupti.so` using `LD_LIBRARY_PATH` as a precautionary safety net. I do not encounter the error `error while loading shared libraries: libcupti.so.12` for the Cuda component tests, but I did encounter it with the sample codes in CUPTI.
- Use `module unload glibc`
Thank you to Geri for discussing the …

PAPI CI: Explicitly set path to `libcupti.so` and `libcudart.so` to avoid error while loading shared libraries

---

src/papi_internal.c

**BACKGROUND**:
Currently in the master branch, an event name will be converted to an event code internally by either calling the function `ntv_name_to_code` if the component supports it or using the workaround if it does not:
```c
do { 
// save event code so components can get it with call to: _papi_hwi_get_papi_event_code()
_papi_hwi_set_papi_event_code(i, 0);
retval = _papi_hwd[cidx]->ntv_code_to_name(i, name, sizeof(name));
/* printf("%#x\nname =|%s|\ninput=|%s|\n", i, name, in); */
if ( retval == PAPI_OK && in != NULL) {
if ( strcasecmp( name, in ) == 0 ) {
*out = _papi_hwi_native_to_eventcode(cidx, i, -1, name);
free (full_event_name);
INTDBG("EXIT: PAPI_OK, event: %s, code: %#x\n", in, *out);
return PAPI_OK;
}    
retval = PAPI_ENOEVNT;
} else {
*out = 0; 
retval = PAPI_ENOEVNT; …
```

papi_internal: Change strcasecmp to strcmp
