src/components/intel_gpu/Rules.intel_gpu, src/components/intel_gpu/tests/Makefile
=> Remove intel_gpu UPC dependency

.github/pull_request_template.md
Add PR author's checklist for github
=> PR author's checklist

.github/workflows/clang_analysis.sh, .github/workflows/main.yml
Implement clang static code analysis from LLVM "scan-build" utility.
=> Implementing clang static code analysis

src/components/rocm/rocp.c
`librocprofiler64.so` was a linker script in 5.6 which was not be able to `dlopen`ed. In 5.7 this has vanished completely, thus try `.so.1` first.
=> rocm: prefer librocprofiler64.so.1

src/components/cuda/cupti_profiler.c
Fixes cuda component enumeration as pointed out by [issue 79](https://github.com/icl-utk-edu/papi/issues/79)
=> cuda: fix event enumeration

src/counter_analysis_toolkit/main.c, src/counter_analysis_toolkit/params.h
- Add a command-line flag for the instructions benchmark to the usage
message.
- Add an optional command-line flag for the path to the configuration
file. This is useful on systems which do not assume the work directory is
where the .cat_cfg file is located.
These changes have been tested on the Intel Sapphire Rapids
architecture.
=> cat: miscellaneous updates

src/components/sde/tests/Minimal/Minimal_Test.c
This PR fixes a pointer in sde Minimal_Test case
=> sde: Fix Minimal_Test.c handle pointer

src/counter_analysis_toolkit/main.c
=> CAT: Add missing option in the usage output.

src/components/rocm/roc_profiler.c
Fix minor bugs that cause:
1. intercept mode counters to read 0; and 
2. intercept mode reset function only reset part of the counters. 
=> Fix intercept mode bugs

src/components/rocm/README.md
Clarify how the component accesses available devices through the runtime system and how this can be affected by resource partitioning at the resource manager level using selected environment variables.
Addresses issue #73 
=> rocm: extend README with device partitioning information

src/counter_analysis_toolkit/timing_kernels.c
CAT: Initialize variables to suppress warnings, and move them to correct scope.
=> CAT: Initialize variables properly.

src/components/intel_gpu/README.md
Fix small typo in the README for the Intel GPU component.
=> intel_gpu: fix small typo

src/counter_analysis_toolkit/main.c
Various updates for MPI builds of CAT.
=> 2023.12.06 CAT MPI fixes

src/counter_analysis_toolkit/dcache.c, src/counter_analysis_toolkit/dcache.h, src/counter_analysis_toolkit/driver.h, src/counter_analysis_toolkit/gen_seq_dlopen.sh, src/counter_analysis_toolkit/hw_desc.h, src/counter_analysis_toolkit/main.c, src/counter_analysis_toolkit/prepareArray.c, src/counter_analysis_toolkit/timing_kernels.c
Various optimizations and logic fixes to the CAT data and instruction cache benchmarks.
=> 2023.12.12 CAT opts and bug fixes

src/counter_analysis_toolkit/dcache.c, src/counter_analysis_toolkit/dcache.h, src/counter_analysis_toolkit/main.c, src/counter_analysis_toolkit/timing_kernels.c, src/counter_analysis_toolkit/timing_kernels.h
=> 2024.01.12 CAT data cache benchmark improvements

src/components/sde/tests/Minimal/Minimal_Test++.cpp, src/components/sde/tests/Simple2/Simple2_Driver++.cpp, src/components/sde/tests/Simple2/Simple2_Lib++.cpp, src/components/sde/tests/Simple2/simple2.hpp
The updated version of the example uses classes and looks like proper C++ much more than the previous version. However, the functionality has remained the same.
=> SDE: Updated the C++ version of the tests.

src/sde_lib/sde_lib_datastructures.c
The previous check would put elements in the overflow list, even in cases where there was room in the bucket that the hash function points to. The updated code gives priority to the bucket. This was a potential performance issue, not a correctness bug.
=> sde_lib: Improved bucket utilization of hash table.

src/components/sde/tests/Counting_Set/CountingSet_Lib.c
By varying the pressure on different buckets we increase the chance of catching hash table bugs.
=> SDE tests: Add more randomness to the test.

src/components/sde/sde.c
=> SDE: Adding ntv_code_to_info functionality.

README.md
Edit to the README to point to the new live FAQ webpage.
=> readme: updated FAQ page

src/components/sysdetect/arm_cpu_utils.c
Add cache information for ARM Neoverse V2, per the Reference Manual: https://developer.arm.com/documentation/102375/0002?lang=en
These changes have been tested on the ARM Neoverse V2 architecture.
=> sysdetect: add support for ARM Neoverse V2

README.md
=> Updated license.

README.md
Updates README, so the documentation link is at a more visible location. Moves the Papers and Presentation link down to resources.
=> README.md: Move Documentation and Papers and Presentation link

doc/Doxyfile-common, doc/Doxyfile-man3, man/man3/papi_hl_output_writer_Sum_Counter.3, man/man3/papi_hl_output_writer_Sum_Counters.3, src/high-level/scripts/papi_hl_output_writer.py
This PR will address two items: 
1. Adding documentation to `papi_hl_output_writer.py`. Documentation is added via use of Doxygen. 
2. Adding `papi_hl_output_writer.py` to Programmers Manual. 
=> Adding documentation via Doxygen to papi_hl_output_writer.py

src/counter_analysis_toolkit/Makefile, src/counter_analysis_toolkit/instructions.c
Additional instruction kernels that perform integer arithmetic (add/sub/mul/div) and a new FP FMA kernel.
=> CAT: New instruction benchmarks for FMA and Int.

src/components/rocp_sdk/sdk_class.cpp
=> rocprof_sdk: Propagate error when obtaining function pointers

src/components/rocp_sdk/sdk_class.cpp
=> rocp_sdk: Ensure context is valid and active when stopping

.github/workflows/ci_papi_framework.sh, .github/workflows/papi_framework_workflow.yml
Update the GitHub CI to resolve bug with Infiniband.
=> GitHub CI: Update GitHub CI to Resolve Infiniband Bug

src/components/rapl/linux-rapl.c
Add support for Intel Comet Lake S/H in the RAPL component.
=> Add support for Intel Comet Lake S/H in RAPL component.

src/components/cuda/cupti_profiler.c
`cuptip_evt_code_to_info` did not consider the flag case for `(STAT_FLAG|DEVICE_FLAG)`. Tested on Nvidia Hopper and Ampere architecutre. The bug can be replicated using the following reproducer:
```
int retval;
retval = PAPI_library_init(PAPI_VER_CURRENT);
if (retval != PAPI_VER_CURRENT) {
printf("Failed init: %d\n", retval);
exit(1);
}
int code;
char *evt = "cuda:::sm__sass_thread_inst_executed_op_hfma_pred_on:stat=sum:device=0";
int status = PAPI_event_name_to_code(evt, &code);
if( status != PAPI_OK ) {
printf("Error with PAPI_event_name_to_code: %d\n", status);
exit(1);
}
PAPI_event_info_t info;
status = PAPI_get_event_info( code, &info );
if( status != PAPI_OK ) {
printf("Error with PAPI_get_event_info: %d\n", status);
exit(1);
}
```
_Why_ this PR exists. Reference all relevant …
=> cuda: Adding stat|device case to code_to_info

papi.spec
Added logic to the papi.spec file so that when creating RPMs that include rocm_smi, the necessary environment variables (e.g. paths) can be set to the appropriate values.
=> .SPEC: Logic for setting rocm_smi env. variables.

src/components/rocm_smi/tests/rocm_smi_writeTests.cpp
- `rocm_smi_writeTests.cpp` failed due to:
- Hard coded event names that do not exist
- Excess code that is not used 
1.  **Removed HIP Kernel:** Eliminated the code not used.
2.  **Test:** Now properly tests PAPI read/write for the rocm_smi component(`perf_level`, `power_cap`, `fan_speed`).
3.  **Stages:** A read -> write -> verify -> revert -> verify sequence for the targeted settings.
The changes in PR353 is needed to test PR352. 
- When running with root permissions
- When running without root permissions
_Commits_ have a body (whenever relevant) containing a …
=> rocm_smi: Update write tests

src/components/rocm_smi/rocs.c
Adding fan speed control capabilities and extra return check
The `rocm_smi` component in `rocs.c` needed to be updated regarding fan speed control and return values. 
- The `access_rsmi_dev_fan_speed` function did not correctly handle setting the fan speed:
- The function is mapped in the event table to handle both `"rsmi_dev_fan_speed_get"` and `"rsmi_dev_fan_speed_set"` events.
- The function's implementation only contained logic to call `rsmi_dev_fan_speed_get_p` when the mode is `ROCS_ACCESS_MODE__READ`. It correctly checks the status for this *get* operation, and now it also correctly checks and sets the status for the *set* operation.
- Added extra return value checks for permissions.
_Why_ this PR exists. Reference all relevant information, including _background_, _issues_, _test …
=> rocm_smi: Add proper fan_speed access, control, and return

src/components/cuda/tests/test_multipass_event_fail.cu
It was reported that the test `test_multipass_event_fail` was failing on Guyot (8 * A100s) when providing events that do not require multiple passes and events that do require multiple passes. This PR updates `test_multipass_event_fail` to be more robust by:
- Updating the conditional checks
- Allowing events that do not require multiple passes to be added and pass
- With an event that does not require multiple passes
```
[ICL:methane tests]$ srun --nodelist=guyot ./test_multipass_event_fail cuda:::dram__bytes:stat:device=2
LOG: test_PAPI_add_event: Entering.
PASSED test_PAPI_add_event
LOG: test_PAPI_add_named_event: Entering.
PASSED test_PAPI_add_named_event
LOG: test_PAPI_add_events: Entering.
PASSED test_PAPI_add_events with 1 of 1 events succesfully added.
PASSED
```
- With an event …
=> Cuda Component: Update the error checks in the test test_multipass_event_fail

src/components/rocp_sdk/rocp_sdk.c
=> ROCP_SDK: Suppress ROCprofiler-SDK warnings.

src/components/rocp_sdk/sdk_class.cpp, src/components/rocp_sdk/sdk_class.hpp
=> ROCP_SDK: Enable default dlopen() paths, and cleaner error handling.

src/components/rocp_sdk/sdk_class.hpp
=> ROCP_SDK: protect the included papi headers from C++

src/papi_memory.c, src/papi_memory.h
=> HEADERS: __FILE__ is "const char *", not "char *"

src/utils/papi_avail.c
Various cleanups to address warnings introduced in PR #284.
These changes have been tested on systems containing the NVIDIA Hopper and Blackwell architectures.
=> 2025.05.13 component preset cleanups

src/components/rocp_sdk/rocp_sdk.c
In the rocp_sdk component, the search path for the library libhsa-runtime64.so should look under PAPI_ROCM_ROOT instead of PAPI_ROCP_SDK_ROOT because the library is provided by ROCM base package. To facility this for users, we will search under PAPI_ROCP_SDK_ROOT, then under PAPI_ROCM_ROOT, and then we will allow the OS to try to find the library for us.
=> New search procedure for libhsa library

src/components/rocp_sdk/rocp_sdk.c
=> ROCP_SDK: Handle case where all events are removed.

RELEASENOTES.txt
Prepared Release Notes for PAPI 7.2.0 release.
Release Notes for PAPI 7.2.0 release.
=> Prepared Release Notes for PAPI 7.2.0 release.

src/components/rocp_sdk/sdk_class.cpp, src/components/rocp_sdk/sdk_class.hpp
- Support ROCm 7 (ROCprofiler SDK 1.x) by trying {create,destroy}_{counter,profile}_config at runtime.
- Switch to new _cb callback typedefs with version guards.
- Keep backward compatibility with pre-7.0 SDKs.
- Built and ran on AMD Instinct MI300; papi_component_avail shows rocp_sdk active.
=> rocp_sdk: add multi-alias dlsym + *_cb typedefs for ROCm 7.0.0

src/components/perf_event/perf_event.c
PR #477 introduced a bug that resulted in the `PAPI_REFRESH_VALUE` not being defined for an architecture of aarch64. Specifically looking at the following block of code where the `PAPI_REFRESH_VALUE` was now defined in this PR:
```c
#if defined(__powerpc__)
#define PAPI_REFRESH_VALUE 0
#define __NR_capget 183
#elif defined(__x86_64__)
#define PAPI_REFRESH_VALUE 1
#define __NR_capget 125
#elif defined(__i386__)
#define PAPI_REFRESH_VALUE 1
#define __NR_capget 184
#elif defined(__arm__)
#define PAPI_REFRESH_VALUE 1
#define __NR_capget 184+0x900000
#endif
```
There is no `else` to catch a fall through case, e.g.:
```c
#else
#define PAPI_REFRESH_VALUE 1
#endif
```
To resolve this bug, the following two items were done:
1. Go back to the original `if defined` for `PAPI_REFRESH_VALUE`, e.g.: …
=> perf_event: Use old `if defined` check for PAPI_REFRESH_VALUE and wrap capget code with `if defined`
